/*
Safe People Registry API

Testing ValidationLogWithCommentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package safepeopleregistry-api-sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/HDRUK/safepeopleregistry-api-go-sdk"
)

func Test_safepeopleregistry-api-sdk_ValidationLogWithCommentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ValidationLogWithCommentsAPIService ValidationLogWithCommentsIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.ValidationLogWithCommentsAPI.ValidationLogWithCommentsIndex(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
