/*
Safe People Registry API

Testing ValidationLogCommentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package safepeopleregistry-api-sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/HDRUK/safepeopleregistry-api-go-sdk"
)

func Test_safepeopleregistry-api-sdk_ValidationLogCommentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ValidationLogCommentsAPIService ValidationLogCommentsComments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.ValidationLogCommentsAPI.ValidationLogCommentsComments(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ValidationLogCommentsAPIService ValidationLogCommentsDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.ValidationLogCommentsAPI.ValidationLogCommentsDestroy(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ValidationLogCommentsAPIService ValidationLogCommentsShow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.ValidationLogCommentsAPI.ValidationLogCommentsShow(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ValidationLogCommentsAPIService ValidationLogCommentsStore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ValidationLogCommentsAPI.ValidationLogCommentsStore(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ValidationLogCommentsAPIService ValidationLogCommentsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.ValidationLogCommentsAPI.ValidationLogCommentsUpdate(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
