/*
Safe People Registry API

Testing FeatureAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package safepeopleregistrysdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/HDRUK/safepeopleregistry-api-go-sdk"
)

func Test_safepeopleregistrysdk_FeatureAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FeatureAPIService FeatureIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FeatureAPI.FeatureIndex(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
