/*
Safe People Registry API

Testing CustodianProjectUsersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package safepeopleregistry-api-sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/HDRUK/safepeopleregistry-api-go-sdk"
)

func Test_safepeopleregistry-api-sdk_CustodianProjectUsersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CustodianProjectUsersAPIService CustodianProjectUsersIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var custodianId int32

		resp, httpRes, err := apiClient.CustodianProjectUsersAPI.CustodianProjectUsersIndex(context.Background(), custodianId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustodianProjectUsersAPIService CustodianProjectUsersShow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var custodianId int32
		var projectUserId int32

		resp, httpRes, err := apiClient.CustodianProjectUsersAPI.CustodianProjectUsersShow(context.Background(), custodianId, projectUserId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CustodianProjectUsersAPIService CustodianProjectUsersUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var custodianId int32
		var projectUserId int32

		resp, httpRes, err := apiClient.CustodianProjectUsersAPI.CustodianProjectUsersUpdate(context.Background(), custodianId, projectUserId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
