/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// CustodiansAPIService CustodiansAPI service
type CustodiansAPIService service

type ApiCustodiansCreateCustodianValidationChecksRequest struct {
	ctx context.Context
	ApiService *CustodiansAPIService
	custodianId int32
	custodiansCreateCustodianValidationChecksRequest *CustodiansCreateCustodianValidationChecksRequest
}

func (r ApiCustodiansCreateCustodianValidationChecksRequest) CustodiansCreateCustodianValidationChecksRequest(custodiansCreateCustodianValidationChecksRequest CustodiansCreateCustodianValidationChecksRequest) ApiCustodiansCreateCustodianValidationChecksRequest {
	r.custodiansCreateCustodianValidationChecksRequest = &custodiansCreateCustodianValidationChecksRequest
	return r
}

func (r ApiCustodiansCreateCustodianValidationChecksRequest) Execute() (*ValidationCheck, *http.Response, error) {
	return r.ApiService.CustodiansCreateCustodianValidationChecksExecute(r)
}

/*
CustodiansCreateCustodianValidationChecks Assign a validation check to a custodian

Creates a new validation check and assigns it to a specific custodian via the custodian_has_validation_check pivot table.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param custodianId ID of the custodian
 @return ApiCustodiansCreateCustodianValidationChecksRequest
*/
func (a *CustodiansAPIService) CustodiansCreateCustodianValidationChecks(ctx context.Context, custodianId int32) ApiCustodiansCreateCustodianValidationChecksRequest {
	return ApiCustodiansCreateCustodianValidationChecksRequest{
		ApiService: a,
		ctx: ctx,
		custodianId: custodianId,
	}
}

// Execute executes the request
//  @return ValidationCheck
func (a *CustodiansAPIService) CustodiansCreateCustodianValidationChecksExecute(r ApiCustodiansCreateCustodianValidationChecksRequest) (*ValidationCheck, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ValidationCheck
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CustodiansAPIService.CustodiansCreateCustodianValidationChecks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/custodians/{custodianId}/validation_checks"
	localVarPath = strings.Replace(localVarPath, "{"+"custodianId"+"}", url.PathEscape(parameterValueToString(r.custodianId, "custodianId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.custodiansCreateCustodianValidationChecksRequest == nil {
		return localVarReturnValue, nil, reportError("custodiansCreateCustodianValidationChecksRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.custodiansCreateCustodianValidationChecksRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v CustodiansCreateCustodianValidationChecks400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CustodiansGetRules404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCustodiansGetCustodianUsersRequest struct {
	ctx context.Context
	ApiService *CustodiansAPIService
	custodianId int32
}

func (r ApiCustodiansGetCustodianUsersRequest) Execute() (*CustodiansGetCustodianUsers200Response, *http.Response, error) {
	return r.ApiService.CustodiansGetCustodianUsersExecute(r)
}

/*
CustodiansGetCustodianUsers Get list of people for a custodian

Fetches the list of custodian users based on the custodian id.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param custodianId ID of the custodian
 @return ApiCustodiansGetCustodianUsersRequest
*/
func (a *CustodiansAPIService) CustodiansGetCustodianUsers(ctx context.Context, custodianId int32) ApiCustodiansGetCustodianUsersRequest {
	return ApiCustodiansGetCustodianUsersRequest{
		ApiService: a,
		ctx: ctx,
		custodianId: custodianId,
	}
}

// Execute executes the request
//  @return CustodiansGetCustodianUsers200Response
func (a *CustodiansAPIService) CustodiansGetCustodianUsersExecute(r ApiCustodiansGetCustodianUsersRequest) (*CustodiansGetCustodianUsers200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CustodiansGetCustodianUsers200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CustodiansAPIService.CustodiansGetCustodianUsers")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/custodians/{custodianId}/custodian_users"
	localVarPath = strings.Replace(localVarPath, "{"+"custodianId"+"}", url.PathEscape(parameterValueToString(r.custodianId, "custodianId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AccreditationIndexByRegistryId400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CustodiansGetCustodianUsers404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCustodiansGetCustodianValidationChecksRequest struct {
	ctx context.Context
	ApiService *CustodiansAPIService
	custodianId int32
}

func (r ApiCustodiansGetCustodianValidationChecksRequest) Execute() ([]ValidationCheck, *http.Response, error) {
	return r.ApiService.CustodiansGetCustodianValidationChecksExecute(r)
}

/*
CustodiansGetCustodianValidationChecks Get validation checks assigned to a custodian

Returns the list of validation checks associated with a specific custodian.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param custodianId ID of the custodian
 @return ApiCustodiansGetCustodianValidationChecksRequest
*/
func (a *CustodiansAPIService) CustodiansGetCustodianValidationChecks(ctx context.Context, custodianId int32) ApiCustodiansGetCustodianValidationChecksRequest {
	return ApiCustodiansGetCustodianValidationChecksRequest{
		ApiService: a,
		ctx: ctx,
		custodianId: custodianId,
	}
}

// Execute executes the request
//  @return []ValidationCheck
func (a *CustodiansAPIService) CustodiansGetCustodianValidationChecksExecute(r ApiCustodiansGetCustodianValidationChecksRequest) ([]ValidationCheck, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ValidationCheck
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CustodiansAPIService.CustodiansGetCustodianValidationChecks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/custodians/{custodianId}/validation_checks"
	localVarPath = strings.Replace(localVarPath, "{"+"custodianId"+"}", url.PathEscape(parameterValueToString(r.custodianId, "custodianId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AccreditationIndexByRegistryId400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CustodiansGetRules404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCustodiansGetOrganisationUsersRequest struct {
	ctx context.Context
	ApiService *CustodiansAPIService
	custodianId int32
	organisationId int32
}

func (r ApiCustodiansGetOrganisationUsersRequest) Execute() (*CustodiansGetOrganisationUsers200Response, *http.Response, error) {
	return r.ApiService.CustodiansGetOrganisationUsersExecute(r)
}

/*
CustodiansGetOrganisationUsers Get list of people for organisation

Fetches the list of users associated with the given custodian and organisations IDs.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param custodianId ID of the custodian
 @param organisationId ID of the organisation
 @return ApiCustodiansGetOrganisationUsersRequest
*/
func (a *CustodiansAPIService) CustodiansGetOrganisationUsers(ctx context.Context, custodianId int32, organisationId int32) ApiCustodiansGetOrganisationUsersRequest {
	return ApiCustodiansGetOrganisationUsersRequest{
		ApiService: a,
		ctx: ctx,
		custodianId: custodianId,
		organisationId: organisationId,
	}
}

// Execute executes the request
//  @return CustodiansGetOrganisationUsers200Response
func (a *CustodiansAPIService) CustodiansGetOrganisationUsersExecute(r ApiCustodiansGetOrganisationUsersRequest) (*CustodiansGetOrganisationUsers200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CustodiansGetOrganisationUsers200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CustodiansAPIService.CustodiansGetOrganisationUsers")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/custodians/{custodianId}/organisations/{organisationId}/users"
	localVarPath = strings.Replace(localVarPath, "{"+"custodianId"+"}", url.PathEscape(parameterValueToString(r.custodianId, "custodianId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"organisationId"+"}", url.PathEscape(parameterValueToString(r.organisationId, "organisationId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AccreditationIndexByRegistryId400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CustodiansGetOrganisationUsers404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCustodiansGetRulesRequest struct {
	ctx context.Context
	ApiService *CustodiansAPIService
	id int32
}

func (r ApiCustodiansGetRulesRequest) Execute() (*CustodiansGetRules200Response, *http.Response, error) {
	return r.ApiService.CustodiansGetRulesExecute(r)
}

/*
CustodiansGetRules Get rules for a specific custodian

Fetches the list of rules associated with the given custodian ID.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id ID of the custodian
 @return ApiCustodiansGetRulesRequest
*/
func (a *CustodiansAPIService) CustodiansGetRules(ctx context.Context, id int32) ApiCustodiansGetRulesRequest {
	return ApiCustodiansGetRulesRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return CustodiansGetRules200Response
func (a *CustodiansAPIService) CustodiansGetRulesExecute(r ApiCustodiansGetRulesRequest) (*CustodiansGetRules200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CustodiansGetRules200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CustodiansAPIService.CustodiansGetRules")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/custodians/{id}/rules"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AccreditationIndexByRegistryId400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CustodiansGetRules404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCustodiansGetStatusesUsersRequest struct {
	ctx context.Context
	ApiService *CustodiansAPIService
	custodianId int32
	projectUserId int32
}

func (r ApiCustodiansGetStatusesUsersRequest) Execute() (*CustodiansGetOrganisationUsers200Response, *http.Response, error) {
	return r.ApiService.CustodiansGetStatusesUsersExecute(r)
}

/*
CustodiansGetStatusesUsers Get statuses for a user in a project/organisation/custodian

Fetches the user statuses given custodian and organisations and project and user IDs.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param custodianId ID of the custodian
 @param projectUserId ID of the project user
 @return ApiCustodiansGetStatusesUsersRequest
*/
func (a *CustodiansAPIService) CustodiansGetStatusesUsers(ctx context.Context, custodianId int32, projectUserId int32) ApiCustodiansGetStatusesUsersRequest {
	return ApiCustodiansGetStatusesUsersRequest{
		ApiService: a,
		ctx: ctx,
		custodianId: custodianId,
		projectUserId: projectUserId,
	}
}

// Execute executes the request
//  @return CustodiansGetOrganisationUsers200Response
func (a *CustodiansAPIService) CustodiansGetStatusesUsersExecute(r ApiCustodiansGetStatusesUsersRequest) (*CustodiansGetOrganisationUsers200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CustodiansGetOrganisationUsers200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CustodiansAPIService.CustodiansGetStatusesUsers")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/custodians/{custodianId}/projectUsers/{projectUserId}/statuses"
	localVarPath = strings.Replace(localVarPath, "{"+"custodianId"+"}", url.PathEscape(parameterValueToString(r.custodianId, "custodianId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"projectUserId"+"}", url.PathEscape(parameterValueToString(r.projectUserId, "projectUserId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v AccreditationIndexByRegistryId400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CustodiansGetOrganisationUsers404Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
