/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the CustodianModelConfigGetEntityModels200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodianModelConfigGetEntityModels200Response{}

// CustodianModelConfigGetEntityModels200Response struct for CustodianModelConfigGetEntityModels200Response
type CustodianModelConfigGetEntityModels200Response struct {
	Message *string `json:"message,omitempty"`
	Data []CustodianModelConfigGetEntityModels200ResponseDataInner `json:"data,omitempty"`
}

// NewCustodianModelConfigGetEntityModels200Response instantiates a new CustodianModelConfigGetEntityModels200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodianModelConfigGetEntityModels200Response() *CustodianModelConfigGetEntityModels200Response {
	this := CustodianModelConfigGetEntityModels200Response{}
	return &this
}

// NewCustodianModelConfigGetEntityModels200ResponseWithDefaults instantiates a new CustodianModelConfigGetEntityModels200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodianModelConfigGetEntityModels200ResponseWithDefaults() *CustodianModelConfigGetEntityModels200Response {
	this := CustodianModelConfigGetEntityModels200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CustodianModelConfigGetEntityModels200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianModelConfigGetEntityModels200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CustodianModelConfigGetEntityModels200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CustodianModelConfigGetEntityModels200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustodianModelConfigGetEntityModels200Response) GetData() []CustodianModelConfigGetEntityModels200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []CustodianModelConfigGetEntityModels200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianModelConfigGetEntityModels200Response) GetDataOk() ([]CustodianModelConfigGetEntityModels200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustodianModelConfigGetEntityModels200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CustodianModelConfigGetEntityModels200ResponseDataInner and assigns it to the Data field.
func (o *CustodianModelConfigGetEntityModels200Response) SetData(v []CustodianModelConfigGetEntityModels200ResponseDataInner) {
	o.Data = v
}

func (o CustodianModelConfigGetEntityModels200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodianModelConfigGetEntityModels200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCustodianModelConfigGetEntityModels200Response struct {
	value *CustodianModelConfigGetEntityModels200Response
	isSet bool
}

func (v NullableCustodianModelConfigGetEntityModels200Response) Get() *CustodianModelConfigGetEntityModels200Response {
	return v.value
}

func (v *NullableCustodianModelConfigGetEntityModels200Response) Set(val *CustodianModelConfigGetEntityModels200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianModelConfigGetEntityModels200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianModelConfigGetEntityModels200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianModelConfigGetEntityModels200Response(val *CustodianModelConfigGetEntityModels200Response) *NullableCustodianModelConfigGetEntityModels200Response {
	return &NullableCustodianModelConfigGetEntityModels200Response{value: val, isSet: true}
}

func (v NullableCustodianModelConfigGetEntityModels200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianModelConfigGetEntityModels200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


