/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the CustodianUserBulkStoreRequestUsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodianUserBulkStoreRequestUsersInner{}

// CustodianUserBulkStoreRequestUsersInner struct for CustodianUserBulkStoreRequestUsersInner
type CustodianUserBulkStoreRequestUsersInner struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Email *string `json:"email,omitempty"`
	Permission *string `json:"permission,omitempty"`
}

// NewCustodianUserBulkStoreRequestUsersInner instantiates a new CustodianUserBulkStoreRequestUsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodianUserBulkStoreRequestUsersInner() *CustodianUserBulkStoreRequestUsersInner {
	this := CustodianUserBulkStoreRequestUsersInner{}
	return &this
}

// NewCustodianUserBulkStoreRequestUsersInnerWithDefaults instantiates a new CustodianUserBulkStoreRequestUsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodianUserBulkStoreRequestUsersInnerWithDefaults() *CustodianUserBulkStoreRequestUsersInner {
	this := CustodianUserBulkStoreRequestUsersInner{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *CustodianUserBulkStoreRequestUsersInner) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *CustodianUserBulkStoreRequestUsersInner) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *CustodianUserBulkStoreRequestUsersInner) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *CustodianUserBulkStoreRequestUsersInner) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CustodianUserBulkStoreRequestUsersInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CustodianUserBulkStoreRequestUsersInner) SetEmail(v string) {
	o.Email = &v
}

// GetPermission returns the Permission field value if set, zero value otherwise.
func (o *CustodianUserBulkStoreRequestUsersInner) GetPermission() string {
	if o == nil || IsNil(o.Permission) {
		var ret string
		return ret
	}
	return *o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) GetPermissionOk() (*string, bool) {
	if o == nil || IsNil(o.Permission) {
		return nil, false
	}
	return o.Permission, true
}

// HasPermission returns a boolean if a field has been set.
func (o *CustodianUserBulkStoreRequestUsersInner) HasPermission() bool {
	if o != nil && !IsNil(o.Permission) {
		return true
	}

	return false
}

// SetPermission gets a reference to the given string and assigns it to the Permission field.
func (o *CustodianUserBulkStoreRequestUsersInner) SetPermission(v string) {
	o.Permission = &v
}

func (o CustodianUserBulkStoreRequestUsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodianUserBulkStoreRequestUsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Permission) {
		toSerialize["permission"] = o.Permission
	}
	return toSerialize, nil
}

type NullableCustodianUserBulkStoreRequestUsersInner struct {
	value *CustodianUserBulkStoreRequestUsersInner
	isSet bool
}

func (v NullableCustodianUserBulkStoreRequestUsersInner) Get() *CustodianUserBulkStoreRequestUsersInner {
	return v.value
}

func (v *NullableCustodianUserBulkStoreRequestUsersInner) Set(val *CustodianUserBulkStoreRequestUsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianUserBulkStoreRequestUsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianUserBulkStoreRequestUsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianUserBulkStoreRequestUsersInner(val *CustodianUserBulkStoreRequestUsersInner) *NullableCustodianUserBulkStoreRequestUsersInner {
	return &NullableCustodianUserBulkStoreRequestUsersInner{value: val, isSet: true}
}

func (v NullableCustodianUserBulkStoreRequestUsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianUserBulkStoreRequestUsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


