/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the CustodianUserBulkStoreRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodianUserBulkStoreRequest{}

// CustodianUserBulkStoreRequest struct for CustodianUserBulkStoreRequest
type CustodianUserBulkStoreRequest struct {
	Users []CustodianUserBulkStoreRequestUsersInner `json:"users,omitempty"`
}

// NewCustodianUserBulkStoreRequest instantiates a new CustodianUserBulkStoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodianUserBulkStoreRequest() *CustodianUserBulkStoreRequest {
	this := CustodianUserBulkStoreRequest{}
	return &this
}

// NewCustodianUserBulkStoreRequestWithDefaults instantiates a new CustodianUserBulkStoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodianUserBulkStoreRequestWithDefaults() *CustodianUserBulkStoreRequest {
	this := CustodianUserBulkStoreRequest{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *CustodianUserBulkStoreRequest) GetUsers() []CustodianUserBulkStoreRequestUsersInner {
	if o == nil || IsNil(o.Users) {
		var ret []CustodianUserBulkStoreRequestUsersInner
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUserBulkStoreRequest) GetUsersOk() ([]CustodianUserBulkStoreRequestUsersInner, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *CustodianUserBulkStoreRequest) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []CustodianUserBulkStoreRequestUsersInner and assigns it to the Users field.
func (o *CustodianUserBulkStoreRequest) SetUsers(v []CustodianUserBulkStoreRequestUsersInner) {
	o.Users = v
}

func (o CustodianUserBulkStoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodianUserBulkStoreRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableCustodianUserBulkStoreRequest struct {
	value *CustodianUserBulkStoreRequest
	isSet bool
}

func (v NullableCustodianUserBulkStoreRequest) Get() *CustodianUserBulkStoreRequest {
	return v.value
}

func (v *NullableCustodianUserBulkStoreRequest) Set(val *CustodianUserBulkStoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianUserBulkStoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianUserBulkStoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianUserBulkStoreRequest(val *CustodianUserBulkStoreRequest) *NullableCustodianUserBulkStoreRequest {
	return &NullableCustodianUserBulkStoreRequest{value: val, isSet: true}
}

func (v NullableCustodianUserBulkStoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianUserBulkStoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


