/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ValidationCheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationCheck{}

// ValidationCheck Model representing validation checks
type ValidationCheck struct {
	// Unique identifier for the validation check
	Id *int32 `json:"id,omitempty"`
	// Name of the validation check
	Name string `json:"name"`
	// Description of the validation check
	Description string `json:"description"`
	// Context to which the validation check applies
	AppliesTo string `json:"applies_to"`
	// Indicates whether the validation check is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// Timestamp when the validation check was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Timestamp when the validation check was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Custodian id or null
	CustodianId *int32 `json:"custodian_id,omitempty"`
}

type _ValidationCheck ValidationCheck

// NewValidationCheck instantiates a new ValidationCheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationCheck(name string, description string, appliesTo string) *ValidationCheck {
	this := ValidationCheck{}
	this.Name = name
	this.Description = description
	this.AppliesTo = appliesTo
	return &this
}

// NewValidationCheckWithDefaults instantiates a new ValidationCheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationCheckWithDefaults() *ValidationCheck {
	this := ValidationCheck{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ValidationCheck) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ValidationCheck) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ValidationCheck) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *ValidationCheck) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ValidationCheck) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ValidationCheck) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ValidationCheck) SetDescription(v string) {
	o.Description = v
}

// GetAppliesTo returns the AppliesTo field value
func (o *ValidationCheck) GetAppliesTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppliesTo
}

// GetAppliesToOk returns a tuple with the AppliesTo field value
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetAppliesToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppliesTo, true
}

// SetAppliesTo sets field value
func (o *ValidationCheck) SetAppliesTo(v string) {
	o.AppliesTo = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ValidationCheck) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ValidationCheck) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ValidationCheck) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ValidationCheck) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ValidationCheck) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ValidationCheck) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ValidationCheck) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ValidationCheck) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ValidationCheck) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCustodianId returns the CustodianId field value if set, zero value otherwise.
func (o *ValidationCheck) GetCustodianId() int32 {
	if o == nil || IsNil(o.CustodianId) {
		var ret int32
		return ret
	}
	return *o.CustodianId
}

// GetCustodianIdOk returns a tuple with the CustodianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetCustodianIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CustodianId) {
		return nil, false
	}
	return o.CustodianId, true
}

// HasCustodianId returns a boolean if a field has been set.
func (o *ValidationCheck) HasCustodianId() bool {
	if o != nil && !IsNil(o.CustodianId) {
		return true
	}

	return false
}

// SetCustodianId gets a reference to the given int32 and assigns it to the CustodianId field.
func (o *ValidationCheck) SetCustodianId(v int32) {
	o.CustodianId = &v
}

func (o ValidationCheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationCheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["applies_to"] = o.AppliesTo
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.CustodianId) {
		toSerialize["custodian_id"] = o.CustodianId
	}
	return toSerialize, nil
}

func (o *ValidationCheck) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"applies_to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationCheck := _ValidationCheck{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidationCheck)

	if err != nil {
		return err
	}

	*o = ValidationCheck(varValidationCheck)

	return err
}

type NullableValidationCheck struct {
	value *ValidationCheck
	isSet bool
}

func (v NullableValidationCheck) Get() *ValidationCheck {
	return v.value
}

func (v *NullableValidationCheck) Set(val *ValidationCheck) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationCheck) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationCheck(val *ValidationCheck) *NullableValidationCheck {
	return &NullableValidationCheck{value: val, isSet: true}
}

func (v NullableValidationCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


