/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the ProjectIndex200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectIndex200ResponseData{}

// ProjectIndex200ResponseData struct for ProjectIndex200ResponseData
type ProjectIndex200ResponseData struct {
	Id *int32 `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	RegistryId *int32 `json:"registry_id,omitempty"`
	Name *string `json:"name,omitempty"`
	PublicBenefit *string `json:"public_benefit,omitempty"`
	RunsTo *string `json:"runs_to,omitempty"`
}

// NewProjectIndex200ResponseData instantiates a new ProjectIndex200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectIndex200ResponseData() *ProjectIndex200ResponseData {
	this := ProjectIndex200ResponseData{}
	return &this
}

// NewProjectIndex200ResponseDataWithDefaults instantiates a new ProjectIndex200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectIndex200ResponseDataWithDefaults() *ProjectIndex200ResponseData {
	this := ProjectIndex200ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProjectIndex200ResponseData) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ProjectIndex200ResponseData) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ProjectIndex200ResponseData) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetRegistryId returns the RegistryId field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetRegistryId() int32 {
	if o == nil || IsNil(o.RegistryId) {
		var ret int32
		return ret
	}
	return *o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetRegistryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistryId) {
		return nil, false
	}
	return o.RegistryId, true
}

// HasRegistryId returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasRegistryId() bool {
	if o != nil && !IsNil(o.RegistryId) {
		return true
	}

	return false
}

// SetRegistryId gets a reference to the given int32 and assigns it to the RegistryId field.
func (o *ProjectIndex200ResponseData) SetRegistryId(v int32) {
	o.RegistryId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectIndex200ResponseData) SetName(v string) {
	o.Name = &v
}

// GetPublicBenefit returns the PublicBenefit field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetPublicBenefit() string {
	if o == nil || IsNil(o.PublicBenefit) {
		var ret string
		return ret
	}
	return *o.PublicBenefit
}

// GetPublicBenefitOk returns a tuple with the PublicBenefit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetPublicBenefitOk() (*string, bool) {
	if o == nil || IsNil(o.PublicBenefit) {
		return nil, false
	}
	return o.PublicBenefit, true
}

// HasPublicBenefit returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasPublicBenefit() bool {
	if o != nil && !IsNil(o.PublicBenefit) {
		return true
	}

	return false
}

// SetPublicBenefit gets a reference to the given string and assigns it to the PublicBenefit field.
func (o *ProjectIndex200ResponseData) SetPublicBenefit(v string) {
	o.PublicBenefit = &v
}

// GetRunsTo returns the RunsTo field value if set, zero value otherwise.
func (o *ProjectIndex200ResponseData) GetRunsTo() string {
	if o == nil || IsNil(o.RunsTo) {
		var ret string
		return ret
	}
	return *o.RunsTo
}

// GetRunsToOk returns a tuple with the RunsTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectIndex200ResponseData) GetRunsToOk() (*string, bool) {
	if o == nil || IsNil(o.RunsTo) {
		return nil, false
	}
	return o.RunsTo, true
}

// HasRunsTo returns a boolean if a field has been set.
func (o *ProjectIndex200ResponseData) HasRunsTo() bool {
	if o != nil && !IsNil(o.RunsTo) {
		return true
	}

	return false
}

// SetRunsTo gets a reference to the given string and assigns it to the RunsTo field.
func (o *ProjectIndex200ResponseData) SetRunsTo(v string) {
	o.RunsTo = &v
}

func (o ProjectIndex200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectIndex200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.RegistryId) {
		toSerialize["registry_id"] = o.RegistryId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PublicBenefit) {
		toSerialize["public_benefit"] = o.PublicBenefit
	}
	if !IsNil(o.RunsTo) {
		toSerialize["runs_to"] = o.RunsTo
	}
	return toSerialize, nil
}

type NullableProjectIndex200ResponseData struct {
	value *ProjectIndex200ResponseData
	isSet bool
}

func (v NullableProjectIndex200ResponseData) Get() *ProjectIndex200ResponseData {
	return v.value
}

func (v *NullableProjectIndex200ResponseData) Set(val *ProjectIndex200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectIndex200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectIndex200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectIndex200ResponseData(val *ProjectIndex200ResponseData) *NullableProjectIndex200ResponseData {
	return &NullableProjectIndex200ResponseData{value: val, isSet: true}
}

func (v NullableProjectIndex200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectIndex200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


