/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the AffiliationsGetOrganisationAffiliation200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffiliationsGetOrganisationAffiliation200Response{}

// AffiliationsGetOrganisationAffiliation200Response struct for AffiliationsGetOrganisationAffiliation200Response
type AffiliationsGetOrganisationAffiliation200Response struct {
	Message *string `json:"message,omitempty"`
	Data *AffiliationsGetOrganisationAffiliation200ResponseData `json:"data,omitempty"`
}

// NewAffiliationsGetOrganisationAffiliation200Response instantiates a new AffiliationsGetOrganisationAffiliation200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliationsGetOrganisationAffiliation200Response() *AffiliationsGetOrganisationAffiliation200Response {
	this := AffiliationsGetOrganisationAffiliation200Response{}
	return &this
}

// NewAffiliationsGetOrganisationAffiliation200ResponseWithDefaults instantiates a new AffiliationsGetOrganisationAffiliation200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliationsGetOrganisationAffiliation200ResponseWithDefaults() *AffiliationsGetOrganisationAffiliation200Response {
	this := AffiliationsGetOrganisationAffiliation200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AffiliationsGetOrganisationAffiliation200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliationsGetOrganisationAffiliation200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AffiliationsGetOrganisationAffiliation200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AffiliationsGetOrganisationAffiliation200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AffiliationsGetOrganisationAffiliation200Response) GetData() AffiliationsGetOrganisationAffiliation200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret AffiliationsGetOrganisationAffiliation200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliationsGetOrganisationAffiliation200Response) GetDataOk() (*AffiliationsGetOrganisationAffiliation200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AffiliationsGetOrganisationAffiliation200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AffiliationsGetOrganisationAffiliation200ResponseData and assigns it to the Data field.
func (o *AffiliationsGetOrganisationAffiliation200Response) SetData(v AffiliationsGetOrganisationAffiliation200ResponseData) {
	o.Data = &v
}

func (o AffiliationsGetOrganisationAffiliation200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AffiliationsGetOrganisationAffiliation200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAffiliationsGetOrganisationAffiliation200Response struct {
	value *AffiliationsGetOrganisationAffiliation200Response
	isSet bool
}

func (v NullableAffiliationsGetOrganisationAffiliation200Response) Get() *AffiliationsGetOrganisationAffiliation200Response {
	return v.value
}

func (v *NullableAffiliationsGetOrganisationAffiliation200Response) Set(val *AffiliationsGetOrganisationAffiliation200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliationsGetOrganisationAffiliation200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliationsGetOrganisationAffiliation200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliationsGetOrganisationAffiliation200Response(val *AffiliationsGetOrganisationAffiliation200Response) *NullableAffiliationsGetOrganisationAffiliation200Response {
	return &NullableAffiliationsGetOrganisationAffiliation200Response{value: val, isSet: true}
}

func (v NullableAffiliationsGetOrganisationAffiliation200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliationsGetOrganisationAffiliation200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


