/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the ValidationLogCommentsShow400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationLogCommentsShow400Response{}

// ValidationLogCommentsShow400Response struct for ValidationLogCommentsShow400Response
type ValidationLogCommentsShow400Response struct {
	Message *string `json:"message,omitempty"`
}

// NewValidationLogCommentsShow400Response instantiates a new ValidationLogCommentsShow400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationLogCommentsShow400Response() *ValidationLogCommentsShow400Response {
	this := ValidationLogCommentsShow400Response{}
	return &this
}

// NewValidationLogCommentsShow400ResponseWithDefaults instantiates a new ValidationLogCommentsShow400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationLogCommentsShow400ResponseWithDefaults() *ValidationLogCommentsShow400Response {
	this := ValidationLogCommentsShow400Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ValidationLogCommentsShow400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationLogCommentsShow400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ValidationLogCommentsShow400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ValidationLogCommentsShow400Response) SetMessage(v string) {
	o.Message = &v
}

func (o ValidationLogCommentsShow400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationLogCommentsShow400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableValidationLogCommentsShow400Response struct {
	value *ValidationLogCommentsShow400Response
	isSet bool
}

func (v NullableValidationLogCommentsShow400Response) Get() *ValidationLogCommentsShow400Response {
	return v.value
}

func (v *NullableValidationLogCommentsShow400Response) Set(val *ValidationLogCommentsShow400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationLogCommentsShow400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationLogCommentsShow400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationLogCommentsShow400Response(val *ValidationLogCommentsShow400Response) *NullableValidationLogCommentsShow400Response {
	return &NullableValidationLogCommentsShow400Response{value: val, isSet: true}
}

func (v NullableValidationLogCommentsShow400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationLogCommentsShow400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


