/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
	"time"
)

// checks if the Resolution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Resolution{}

// Resolution Model representing resolutions
type Resolution struct {
	// Unique identifier for the resolution
	Id *int32 `json:"id,omitempty"`
	// Comment associated with the resolution
	Comment *string `json:"comment,omitempty"`
	// ID of the custodian who resolved the issue
	CustodianBy *int32 `json:"custodian_by,omitempty"`
	// ID of the registry associated with the resolution
	RegistryId *int32 `json:"registry_id,omitempty"`
	// Indicates whether the resolution is resolved
	Resolved *bool `json:"resolved,omitempty"`
	// Timestamp when the resolution was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Timestamp when the resolution was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewResolution instantiates a new Resolution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolution() *Resolution {
	this := Resolution{}
	return &this
}

// NewResolutionWithDefaults instantiates a new Resolution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolutionWithDefaults() *Resolution {
	this := Resolution{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Resolution) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Resolution) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Resolution) SetId(v int32) {
	o.Id = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *Resolution) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *Resolution) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *Resolution) SetComment(v string) {
	o.Comment = &v
}

// GetCustodianBy returns the CustodianBy field value if set, zero value otherwise.
func (o *Resolution) GetCustodianBy() int32 {
	if o == nil || IsNil(o.CustodianBy) {
		var ret int32
		return ret
	}
	return *o.CustodianBy
}

// GetCustodianByOk returns a tuple with the CustodianBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetCustodianByOk() (*int32, bool) {
	if o == nil || IsNil(o.CustodianBy) {
		return nil, false
	}
	return o.CustodianBy, true
}

// HasCustodianBy returns a boolean if a field has been set.
func (o *Resolution) HasCustodianBy() bool {
	if o != nil && !IsNil(o.CustodianBy) {
		return true
	}

	return false
}

// SetCustodianBy gets a reference to the given int32 and assigns it to the CustodianBy field.
func (o *Resolution) SetCustodianBy(v int32) {
	o.CustodianBy = &v
}

// GetRegistryId returns the RegistryId field value if set, zero value otherwise.
func (o *Resolution) GetRegistryId() int32 {
	if o == nil || IsNil(o.RegistryId) {
		var ret int32
		return ret
	}
	return *o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetRegistryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistryId) {
		return nil, false
	}
	return o.RegistryId, true
}

// HasRegistryId returns a boolean if a field has been set.
func (o *Resolution) HasRegistryId() bool {
	if o != nil && !IsNil(o.RegistryId) {
		return true
	}

	return false
}

// SetRegistryId gets a reference to the given int32 and assigns it to the RegistryId field.
func (o *Resolution) SetRegistryId(v int32) {
	o.RegistryId = &v
}

// GetResolved returns the Resolved field value if set, zero value otherwise.
func (o *Resolution) GetResolved() bool {
	if o == nil || IsNil(o.Resolved) {
		var ret bool
		return ret
	}
	return *o.Resolved
}

// GetResolvedOk returns a tuple with the Resolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetResolvedOk() (*bool, bool) {
	if o == nil || IsNil(o.Resolved) {
		return nil, false
	}
	return o.Resolved, true
}

// HasResolved returns a boolean if a field has been set.
func (o *Resolution) HasResolved() bool {
	if o != nil && !IsNil(o.Resolved) {
		return true
	}

	return false
}

// SetResolved gets a reference to the given bool and assigns it to the Resolved field.
func (o *Resolution) SetResolved(v bool) {
	o.Resolved = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Resolution) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Resolution) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Resolution) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Resolution) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Resolution) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Resolution) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Resolution) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Resolution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Resolution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.CustodianBy) {
		toSerialize["custodian_by"] = o.CustodianBy
	}
	if !IsNil(o.RegistryId) {
		toSerialize["registry_id"] = o.RegistryId
	}
	if !IsNil(o.Resolved) {
		toSerialize["resolved"] = o.Resolved
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableResolution struct {
	value *Resolution
	isSet bool
}

func (v NullableResolution) Get() *Resolution {
	return v.value
}

func (v *NullableResolution) Set(val *Resolution) {
	v.value = val
	v.isSet = true
}

func (v NullableResolution) IsSet() bool {
	return v.isSet
}

func (v *NullableResolution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolution(val *Resolution) *NullableResolution {
	return &NullableResolution{value: val, isSet: true}
}

func (v NullableResolution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


