/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User User model
type User struct {
	Id *int32 `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Email *string `json:"email,omitempty"`
	EmailVerifiedAt *string `json:"email_verified_at,omitempty"`
	ConsentScrape *bool `json:"consent_scrape,omitempty"`
	PublicOptIn *bool `json:"public_opt_in,omitempty"`
	DeclarationSigned *bool `json:"declaration_signed,omitempty"`
	OrganisationId *int32 `json:"organisation_id,omitempty"`
	OrcidScanning *int32 `json:"orcid_scanning,omitempty"`
	OrcidScanningCompletedAt *string `json:"orcid_scanning_completed_at,omitempty"`
	Location *string `json:"location,omitempty"`
	TAndCAgreed *bool `json:"t_and_c_agreed,omitempty"`
	TAndCAgreementDate *string `json:"t_and_c_agreement_date,omitempty"`
}

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser() *User {
	this := User{}
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *User) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *User) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *User) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *User) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *User) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *User) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *User) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *User) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *User) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *User) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *User) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *User) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *User) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *User) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *User) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *User) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *User) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *User) SetEmail(v string) {
	o.Email = &v
}

// GetEmailVerifiedAt returns the EmailVerifiedAt field value if set, zero value otherwise.
func (o *User) GetEmailVerifiedAt() string {
	if o == nil || IsNil(o.EmailVerifiedAt) {
		var ret string
		return ret
	}
	return *o.EmailVerifiedAt
}

// GetEmailVerifiedAtOk returns a tuple with the EmailVerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailVerifiedAtOk() (*string, bool) {
	if o == nil || IsNil(o.EmailVerifiedAt) {
		return nil, false
	}
	return o.EmailVerifiedAt, true
}

// HasEmailVerifiedAt returns a boolean if a field has been set.
func (o *User) HasEmailVerifiedAt() bool {
	if o != nil && !IsNil(o.EmailVerifiedAt) {
		return true
	}

	return false
}

// SetEmailVerifiedAt gets a reference to the given string and assigns it to the EmailVerifiedAt field.
func (o *User) SetEmailVerifiedAt(v string) {
	o.EmailVerifiedAt = &v
}

// GetConsentScrape returns the ConsentScrape field value if set, zero value otherwise.
func (o *User) GetConsentScrape() bool {
	if o == nil || IsNil(o.ConsentScrape) {
		var ret bool
		return ret
	}
	return *o.ConsentScrape
}

// GetConsentScrapeOk returns a tuple with the ConsentScrape field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetConsentScrapeOk() (*bool, bool) {
	if o == nil || IsNil(o.ConsentScrape) {
		return nil, false
	}
	return o.ConsentScrape, true
}

// HasConsentScrape returns a boolean if a field has been set.
func (o *User) HasConsentScrape() bool {
	if o != nil && !IsNil(o.ConsentScrape) {
		return true
	}

	return false
}

// SetConsentScrape gets a reference to the given bool and assigns it to the ConsentScrape field.
func (o *User) SetConsentScrape(v bool) {
	o.ConsentScrape = &v
}

// GetPublicOptIn returns the PublicOptIn field value if set, zero value otherwise.
func (o *User) GetPublicOptIn() bool {
	if o == nil || IsNil(o.PublicOptIn) {
		var ret bool
		return ret
	}
	return *o.PublicOptIn
}

// GetPublicOptInOk returns a tuple with the PublicOptIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPublicOptInOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicOptIn) {
		return nil, false
	}
	return o.PublicOptIn, true
}

// HasPublicOptIn returns a boolean if a field has been set.
func (o *User) HasPublicOptIn() bool {
	if o != nil && !IsNil(o.PublicOptIn) {
		return true
	}

	return false
}

// SetPublicOptIn gets a reference to the given bool and assigns it to the PublicOptIn field.
func (o *User) SetPublicOptIn(v bool) {
	o.PublicOptIn = &v
}

// GetDeclarationSigned returns the DeclarationSigned field value if set, zero value otherwise.
func (o *User) GetDeclarationSigned() bool {
	if o == nil || IsNil(o.DeclarationSigned) {
		var ret bool
		return ret
	}
	return *o.DeclarationSigned
}

// GetDeclarationSignedOk returns a tuple with the DeclarationSigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDeclarationSignedOk() (*bool, bool) {
	if o == nil || IsNil(o.DeclarationSigned) {
		return nil, false
	}
	return o.DeclarationSigned, true
}

// HasDeclarationSigned returns a boolean if a field has been set.
func (o *User) HasDeclarationSigned() bool {
	if o != nil && !IsNil(o.DeclarationSigned) {
		return true
	}

	return false
}

// SetDeclarationSigned gets a reference to the given bool and assigns it to the DeclarationSigned field.
func (o *User) SetDeclarationSigned(v bool) {
	o.DeclarationSigned = &v
}

// GetOrganisationId returns the OrganisationId field value if set, zero value otherwise.
func (o *User) GetOrganisationId() int32 {
	if o == nil || IsNil(o.OrganisationId) {
		var ret int32
		return ret
	}
	return *o.OrganisationId
}

// GetOrganisationIdOk returns a tuple with the OrganisationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOrganisationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganisationId) {
		return nil, false
	}
	return o.OrganisationId, true
}

// HasOrganisationId returns a boolean if a field has been set.
func (o *User) HasOrganisationId() bool {
	if o != nil && !IsNil(o.OrganisationId) {
		return true
	}

	return false
}

// SetOrganisationId gets a reference to the given int32 and assigns it to the OrganisationId field.
func (o *User) SetOrganisationId(v int32) {
	o.OrganisationId = &v
}

// GetOrcidScanning returns the OrcidScanning field value if set, zero value otherwise.
func (o *User) GetOrcidScanning() int32 {
	if o == nil || IsNil(o.OrcidScanning) {
		var ret int32
		return ret
	}
	return *o.OrcidScanning
}

// GetOrcidScanningOk returns a tuple with the OrcidScanning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOrcidScanningOk() (*int32, bool) {
	if o == nil || IsNil(o.OrcidScanning) {
		return nil, false
	}
	return o.OrcidScanning, true
}

// HasOrcidScanning returns a boolean if a field has been set.
func (o *User) HasOrcidScanning() bool {
	if o != nil && !IsNil(o.OrcidScanning) {
		return true
	}

	return false
}

// SetOrcidScanning gets a reference to the given int32 and assigns it to the OrcidScanning field.
func (o *User) SetOrcidScanning(v int32) {
	o.OrcidScanning = &v
}

// GetOrcidScanningCompletedAt returns the OrcidScanningCompletedAt field value if set, zero value otherwise.
func (o *User) GetOrcidScanningCompletedAt() string {
	if o == nil || IsNil(o.OrcidScanningCompletedAt) {
		var ret string
		return ret
	}
	return *o.OrcidScanningCompletedAt
}

// GetOrcidScanningCompletedAtOk returns a tuple with the OrcidScanningCompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOrcidScanningCompletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.OrcidScanningCompletedAt) {
		return nil, false
	}
	return o.OrcidScanningCompletedAt, true
}

// HasOrcidScanningCompletedAt returns a boolean if a field has been set.
func (o *User) HasOrcidScanningCompletedAt() bool {
	if o != nil && !IsNil(o.OrcidScanningCompletedAt) {
		return true
	}

	return false
}

// SetOrcidScanningCompletedAt gets a reference to the given string and assigns it to the OrcidScanningCompletedAt field.
func (o *User) SetOrcidScanningCompletedAt(v string) {
	o.OrcidScanningCompletedAt = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *User) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *User) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *User) SetLocation(v string) {
	o.Location = &v
}

// GetTAndCAgreed returns the TAndCAgreed field value if set, zero value otherwise.
func (o *User) GetTAndCAgreed() bool {
	if o == nil || IsNil(o.TAndCAgreed) {
		var ret bool
		return ret
	}
	return *o.TAndCAgreed
}

// GetTAndCAgreedOk returns a tuple with the TAndCAgreed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTAndCAgreedOk() (*bool, bool) {
	if o == nil || IsNil(o.TAndCAgreed) {
		return nil, false
	}
	return o.TAndCAgreed, true
}

// HasTAndCAgreed returns a boolean if a field has been set.
func (o *User) HasTAndCAgreed() bool {
	if o != nil && !IsNil(o.TAndCAgreed) {
		return true
	}

	return false
}

// SetTAndCAgreed gets a reference to the given bool and assigns it to the TAndCAgreed field.
func (o *User) SetTAndCAgreed(v bool) {
	o.TAndCAgreed = &v
}

// GetTAndCAgreementDate returns the TAndCAgreementDate field value if set, zero value otherwise.
func (o *User) GetTAndCAgreementDate() string {
	if o == nil || IsNil(o.TAndCAgreementDate) {
		var ret string
		return ret
	}
	return *o.TAndCAgreementDate
}

// GetTAndCAgreementDateOk returns a tuple with the TAndCAgreementDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTAndCAgreementDateOk() (*string, bool) {
	if o == nil || IsNil(o.TAndCAgreementDate) {
		return nil, false
	}
	return o.TAndCAgreementDate, true
}

// HasTAndCAgreementDate returns a boolean if a field has been set.
func (o *User) HasTAndCAgreementDate() bool {
	if o != nil && !IsNil(o.TAndCAgreementDate) {
		return true
	}

	return false
}

// SetTAndCAgreementDate gets a reference to the given string and assigns it to the TAndCAgreementDate field.
func (o *User) SetTAndCAgreementDate(v string) {
	o.TAndCAgreementDate = &v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.EmailVerifiedAt) {
		toSerialize["email_verified_at"] = o.EmailVerifiedAt
	}
	if !IsNil(o.ConsentScrape) {
		toSerialize["consent_scrape"] = o.ConsentScrape
	}
	if !IsNil(o.PublicOptIn) {
		toSerialize["public_opt_in"] = o.PublicOptIn
	}
	if !IsNil(o.DeclarationSigned) {
		toSerialize["declaration_signed"] = o.DeclarationSigned
	}
	if !IsNil(o.OrganisationId) {
		toSerialize["organisation_id"] = o.OrganisationId
	}
	if !IsNil(o.OrcidScanning) {
		toSerialize["orcid_scanning"] = o.OrcidScanning
	}
	if !IsNil(o.OrcidScanningCompletedAt) {
		toSerialize["orcid_scanning_completed_at"] = o.OrcidScanningCompletedAt
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.TAndCAgreed) {
		toSerialize["t_and_c_agreed"] = o.TAndCAgreed
	}
	if !IsNil(o.TAndCAgreementDate) {
		toSerialize["t_and_c_agreement_date"] = o.TAndCAgreementDate
	}
	return toSerialize, nil
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


