/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation{}

// AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation struct for AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation
type AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation struct {
	Id *int32 `json:"id,omitempty"`
	OrganisationName *string `json:"organisation_name,omitempty"`
	Unclaimed *bool `json:"unclaimed,omitempty"`
	LeadApplicantEmail *string `json:"lead_applicant_email,omitempty"`
}

// NewAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation instantiates a new AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation() *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
	this := AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation{}
	return &this
}

// NewAffiliationsGetOrganisationAffiliation200ResponseDataOrganisationWithDefaults instantiates a new AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliationsGetOrganisationAffiliation200ResponseDataOrganisationWithDefaults() *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
	this := AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) SetId(v int32) {
	o.Id = &v
}

// GetOrganisationName returns the OrganisationName field value if set, zero value otherwise.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetOrganisationName() string {
	if o == nil || IsNil(o.OrganisationName) {
		var ret string
		return ret
	}
	return *o.OrganisationName
}

// GetOrganisationNameOk returns a tuple with the OrganisationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetOrganisationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrganisationName) {
		return nil, false
	}
	return o.OrganisationName, true
}

// HasOrganisationName returns a boolean if a field has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) HasOrganisationName() bool {
	if o != nil && !IsNil(o.OrganisationName) {
		return true
	}

	return false
}

// SetOrganisationName gets a reference to the given string and assigns it to the OrganisationName field.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) SetOrganisationName(v string) {
	o.OrganisationName = &v
}

// GetUnclaimed returns the Unclaimed field value if set, zero value otherwise.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetUnclaimed() bool {
	if o == nil || IsNil(o.Unclaimed) {
		var ret bool
		return ret
	}
	return *o.Unclaimed
}

// GetUnclaimedOk returns a tuple with the Unclaimed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetUnclaimedOk() (*bool, bool) {
	if o == nil || IsNil(o.Unclaimed) {
		return nil, false
	}
	return o.Unclaimed, true
}

// HasUnclaimed returns a boolean if a field has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) HasUnclaimed() bool {
	if o != nil && !IsNil(o.Unclaimed) {
		return true
	}

	return false
}

// SetUnclaimed gets a reference to the given bool and assigns it to the Unclaimed field.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) SetUnclaimed(v bool) {
	o.Unclaimed = &v
}

// GetLeadApplicantEmail returns the LeadApplicantEmail field value if set, zero value otherwise.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetLeadApplicantEmail() string {
	if o == nil || IsNil(o.LeadApplicantEmail) {
		var ret string
		return ret
	}
	return *o.LeadApplicantEmail
}

// GetLeadApplicantEmailOk returns a tuple with the LeadApplicantEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) GetLeadApplicantEmailOk() (*string, bool) {
	if o == nil || IsNil(o.LeadApplicantEmail) {
		return nil, false
	}
	return o.LeadApplicantEmail, true
}

// HasLeadApplicantEmail returns a boolean if a field has been set.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) HasLeadApplicantEmail() bool {
	if o != nil && !IsNil(o.LeadApplicantEmail) {
		return true
	}

	return false
}

// SetLeadApplicantEmail gets a reference to the given string and assigns it to the LeadApplicantEmail field.
func (o *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) SetLeadApplicantEmail(v string) {
	o.LeadApplicantEmail = &v
}

func (o AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrganisationName) {
		toSerialize["organisation_name"] = o.OrganisationName
	}
	if !IsNil(o.Unclaimed) {
		toSerialize["unclaimed"] = o.Unclaimed
	}
	if !IsNil(o.LeadApplicantEmail) {
		toSerialize["lead_applicant_email"] = o.LeadApplicantEmail
	}
	return toSerialize, nil
}

type NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation struct {
	value *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation
	isSet bool
}

func (v NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) Get() *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
	return v.value
}

func (v *NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) Set(val *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation(val *AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) *NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
	return &NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation{value: val, isSet: true}
}

func (v NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliationsGetOrganisationAffiliation200ResponseDataOrganisation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


