/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the FeatureIndex404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureIndex404Response{}

// FeatureIndex404Response struct for FeatureIndex404Response
type FeatureIndex404Response struct {
	Message *string `json:"message,omitempty"`
}

// NewFeatureIndex404Response instantiates a new FeatureIndex404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureIndex404Response() *FeatureIndex404Response {
	this := FeatureIndex404Response{}
	return &this
}

// NewFeatureIndex404ResponseWithDefaults instantiates a new FeatureIndex404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureIndex404ResponseWithDefaults() *FeatureIndex404Response {
	this := FeatureIndex404Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FeatureIndex404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureIndex404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FeatureIndex404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FeatureIndex404Response) SetMessage(v string) {
	o.Message = &v
}

func (o FeatureIndex404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureIndex404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableFeatureIndex404Response struct {
	value *FeatureIndex404Response
	isSet bool
}

func (v NullableFeatureIndex404Response) Get() *FeatureIndex404Response {
	return v.value
}

func (v *NullableFeatureIndex404Response) Set(val *FeatureIndex404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureIndex404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureIndex404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureIndex404Response(val *FeatureIndex404Response) *NullableFeatureIndex404Response {
	return &NullableFeatureIndex404Response{value: val, isSet: true}
}

func (v NullableFeatureIndex404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureIndex404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


