/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the ProjectHasUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectHasUser{}

// ProjectHasUser struct for ProjectHasUser
type ProjectHasUser struct {
	Project *Project `json:"project,omitempty"`
	Role *ProjectRole `json:"role,omitempty"`
	Affiliation *Affiliation `json:"affiliation,omitempty"`
}

// NewProjectHasUser instantiates a new ProjectHasUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectHasUser() *ProjectHasUser {
	this := ProjectHasUser{}
	return &this
}

// NewProjectHasUserWithDefaults instantiates a new ProjectHasUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectHasUserWithDefaults() *ProjectHasUser {
	this := ProjectHasUser{}
	return &this
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ProjectHasUser) GetProject() Project {
	if o == nil || IsNil(o.Project) {
		var ret Project
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHasUser) GetProjectOk() (*Project, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ProjectHasUser) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given Project and assigns it to the Project field.
func (o *ProjectHasUser) SetProject(v Project) {
	o.Project = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ProjectHasUser) GetRole() ProjectRole {
	if o == nil || IsNil(o.Role) {
		var ret ProjectRole
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHasUser) GetRoleOk() (*ProjectRole, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ProjectHasUser) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given ProjectRole and assigns it to the Role field.
func (o *ProjectHasUser) SetRole(v ProjectRole) {
	o.Role = &v
}

// GetAffiliation returns the Affiliation field value if set, zero value otherwise.
func (o *ProjectHasUser) GetAffiliation() Affiliation {
	if o == nil || IsNil(o.Affiliation) {
		var ret Affiliation
		return ret
	}
	return *o.Affiliation
}

// GetAffiliationOk returns a tuple with the Affiliation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHasUser) GetAffiliationOk() (*Affiliation, bool) {
	if o == nil || IsNil(o.Affiliation) {
		return nil, false
	}
	return o.Affiliation, true
}

// HasAffiliation returns a boolean if a field has been set.
func (o *ProjectHasUser) HasAffiliation() bool {
	if o != nil && !IsNil(o.Affiliation) {
		return true
	}

	return false
}

// SetAffiliation gets a reference to the given Affiliation and assigns it to the Affiliation field.
func (o *ProjectHasUser) SetAffiliation(v Affiliation) {
	o.Affiliation = &v
}

func (o ProjectHasUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectHasUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Affiliation) {
		toSerialize["affiliation"] = o.Affiliation
	}
	return toSerialize, nil
}

type NullableProjectHasUser struct {
	value *ProjectHasUser
	isSet bool
}

func (v NullableProjectHasUser) Get() *ProjectHasUser {
	return v.value
}

func (v *NullableProjectHasUser) Set(val *ProjectHasUser) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectHasUser) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectHasUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectHasUser(val *ProjectHasUser) *NullableProjectHasUser {
	return &NullableProjectHasUser{value: val, isSet: true}
}

func (v NullableProjectHasUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectHasUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


