/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the ActionLogsGetEntityActionLog200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionLogsGetEntityActionLog200Response{}

// ActionLogsGetEntityActionLog200Response struct for ActionLogsGetEntityActionLog200Response
type ActionLogsGetEntityActionLog200Response struct {
	Data []ActionLog `json:"data,omitempty"`
}

// NewActionLogsGetEntityActionLog200Response instantiates a new ActionLogsGetEntityActionLog200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionLogsGetEntityActionLog200Response() *ActionLogsGetEntityActionLog200Response {
	this := ActionLogsGetEntityActionLog200Response{}
	return &this
}

// NewActionLogsGetEntityActionLog200ResponseWithDefaults instantiates a new ActionLogsGetEntityActionLog200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionLogsGetEntityActionLog200ResponseWithDefaults() *ActionLogsGetEntityActionLog200Response {
	this := ActionLogsGetEntityActionLog200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ActionLogsGetEntityActionLog200Response) GetData() []ActionLog {
	if o == nil || IsNil(o.Data) {
		var ret []ActionLog
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionLogsGetEntityActionLog200Response) GetDataOk() ([]ActionLog, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ActionLogsGetEntityActionLog200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ActionLog and assigns it to the Data field.
func (o *ActionLogsGetEntityActionLog200Response) SetData(v []ActionLog) {
	o.Data = v
}

func (o ActionLogsGetEntityActionLog200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionLogsGetEntityActionLog200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableActionLogsGetEntityActionLog200Response struct {
	value *ActionLogsGetEntityActionLog200Response
	isSet bool
}

func (v NullableActionLogsGetEntityActionLog200Response) Get() *ActionLogsGetEntityActionLog200Response {
	return v.value
}

func (v *NullableActionLogsGetEntityActionLog200Response) Set(val *ActionLogsGetEntityActionLog200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableActionLogsGetEntityActionLog200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableActionLogsGetEntityActionLog200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionLogsGetEntityActionLog200Response(val *ActionLogsGetEntityActionLog200Response) *NullableActionLogsGetEntityActionLog200Response {
	return &NullableActionLogsGetEntityActionLog200Response{value: val, isSet: true}
}

func (v NullableActionLogsGetEntityActionLog200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionLogsGetEntityActionLog200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


