/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the ProjectHasRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectHasRole{}

// ProjectHasRole Pivot model representing the relationship between projects and roles
type ProjectHasRole struct {
	// ID of the project
	ProjectId *int32 `json:"project_id,omitempty"`
	// ID of the project role
	ProjectRoleId *int32 `json:"project_role_id,omitempty"`
}

// NewProjectHasRole instantiates a new ProjectHasRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectHasRole() *ProjectHasRole {
	this := ProjectHasRole{}
	return &this
}

// NewProjectHasRoleWithDefaults instantiates a new ProjectHasRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectHasRoleWithDefaults() *ProjectHasRole {
	this := ProjectHasRole{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ProjectHasRole) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHasRole) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectHasRole) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *ProjectHasRole) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetProjectRoleId returns the ProjectRoleId field value if set, zero value otherwise.
func (o *ProjectHasRole) GetProjectRoleId() int32 {
	if o == nil || IsNil(o.ProjectRoleId) {
		var ret int32
		return ret
	}
	return *o.ProjectRoleId
}

// GetProjectRoleIdOk returns a tuple with the ProjectRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHasRole) GetProjectRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectRoleId) {
		return nil, false
	}
	return o.ProjectRoleId, true
}

// HasProjectRoleId returns a boolean if a field has been set.
func (o *ProjectHasRole) HasProjectRoleId() bool {
	if o != nil && !IsNil(o.ProjectRoleId) {
		return true
	}

	return false
}

// SetProjectRoleId gets a reference to the given int32 and assigns it to the ProjectRoleId field.
func (o *ProjectHasRole) SetProjectRoleId(v int32) {
	o.ProjectRoleId = &v
}

func (o ProjectHasRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectHasRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.ProjectRoleId) {
		toSerialize["project_role_id"] = o.ProjectRoleId
	}
	return toSerialize, nil
}

type NullableProjectHasRole struct {
	value *ProjectHasRole
	isSet bool
}

func (v NullableProjectHasRole) Get() *ProjectHasRole {
	return v.value
}

func (v *NullableProjectHasRole) Set(val *ProjectHasRole) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectHasRole) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectHasRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectHasRole(val *ProjectHasRole) *NullableProjectHasRole {
	return &NullableProjectHasRole{value: val, isSet: true}
}

func (v NullableProjectHasRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectHasRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


