/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the UserHasCustodianPermission type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserHasCustodianPermission{}

// UserHasCustodianPermission Pivot model representing the relationship between users, custodians, and permissions
type UserHasCustodianPermission struct {
	// ID of the user
	UserId *int32 `json:"user_id,omitempty"`
	// ID of the permission
	PermissionId *int32 `json:"permission_id,omitempty"`
	// ID of the custodian
	CustodianId *int32 `json:"custodian_id,omitempty"`
}

// NewUserHasCustodianPermission instantiates a new UserHasCustodianPermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserHasCustodianPermission() *UserHasCustodianPermission {
	this := UserHasCustodianPermission{}
	return &this
}

// NewUserHasCustodianPermissionWithDefaults instantiates a new UserHasCustodianPermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserHasCustodianPermissionWithDefaults() *UserHasCustodianPermission {
	this := UserHasCustodianPermission{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserHasCustodianPermission) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserHasCustodianPermission) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UserHasCustodianPermission) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *UserHasCustodianPermission) SetUserId(v int32) {
	o.UserId = &v
}

// GetPermissionId returns the PermissionId field value if set, zero value otherwise.
func (o *UserHasCustodianPermission) GetPermissionId() int32 {
	if o == nil || IsNil(o.PermissionId) {
		var ret int32
		return ret
	}
	return *o.PermissionId
}

// GetPermissionIdOk returns a tuple with the PermissionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserHasCustodianPermission) GetPermissionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PermissionId) {
		return nil, false
	}
	return o.PermissionId, true
}

// HasPermissionId returns a boolean if a field has been set.
func (o *UserHasCustodianPermission) HasPermissionId() bool {
	if o != nil && !IsNil(o.PermissionId) {
		return true
	}

	return false
}

// SetPermissionId gets a reference to the given int32 and assigns it to the PermissionId field.
func (o *UserHasCustodianPermission) SetPermissionId(v int32) {
	o.PermissionId = &v
}

// GetCustodianId returns the CustodianId field value if set, zero value otherwise.
func (o *UserHasCustodianPermission) GetCustodianId() int32 {
	if o == nil || IsNil(o.CustodianId) {
		var ret int32
		return ret
	}
	return *o.CustodianId
}

// GetCustodianIdOk returns a tuple with the CustodianId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserHasCustodianPermission) GetCustodianIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CustodianId) {
		return nil, false
	}
	return o.CustodianId, true
}

// HasCustodianId returns a boolean if a field has been set.
func (o *UserHasCustodianPermission) HasCustodianId() bool {
	if o != nil && !IsNil(o.CustodianId) {
		return true
	}

	return false
}

// SetCustodianId gets a reference to the given int32 and assigns it to the CustodianId field.
func (o *UserHasCustodianPermission) SetCustodianId(v int32) {
	o.CustodianId = &v
}

func (o UserHasCustodianPermission) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserHasCustodianPermission) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.PermissionId) {
		toSerialize["permission_id"] = o.PermissionId
	}
	if !IsNil(o.CustodianId) {
		toSerialize["custodian_id"] = o.CustodianId
	}
	return toSerialize, nil
}

type NullableUserHasCustodianPermission struct {
	value *UserHasCustodianPermission
	isSet bool
}

func (v NullableUserHasCustodianPermission) Get() *UserHasCustodianPermission {
	return v.value
}

func (v *NullableUserHasCustodianPermission) Set(val *UserHasCustodianPermission) {
	v.value = val
	v.isSet = true
}

func (v NullableUserHasCustodianPermission) IsSet() bool {
	return v.isSet
}

func (v *NullableUserHasCustodianPermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserHasCustodianPermission(val *UserHasCustodianPermission) *NullableUserHasCustodianPermission {
	return &NullableUserHasCustodianPermission{value: val, isSet: true}
}

func (v NullableUserHasCustodianPermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserHasCustodianPermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


