/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner{}

// ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner struct for ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner
type ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner struct {
	Id *int32 `json:"id,omitempty"`
	OrganisationName *string `json:"organisation_name,omitempty"`
}

// NewProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner instantiates a new ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner() *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner {
	this := ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner{}
	return &this
}

// NewProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInnerWithDefaults instantiates a new ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInnerWithDefaults() *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner {
	this := ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) SetId(v int32) {
	o.Id = &v
}

// GetOrganisationName returns the OrganisationName field value if set, zero value otherwise.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) GetOrganisationName() string {
	if o == nil || IsNil(o.OrganisationName) {
		var ret string
		return ret
	}
	return *o.OrganisationName
}

// GetOrganisationNameOk returns a tuple with the OrganisationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) GetOrganisationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrganisationName) {
		return nil, false
	}
	return o.OrganisationName, true
}

// HasOrganisationName returns a boolean if a field has been set.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) HasOrganisationName() bool {
	if o != nil && !IsNil(o.OrganisationName) {
		return true
	}

	return false
}

// SetOrganisationName gets a reference to the given string and assigns it to the OrganisationName field.
func (o *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) SetOrganisationName(v string) {
	o.OrganisationName = &v
}

func (o ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrganisationName) {
		toSerialize["organisation_name"] = o.OrganisationName
	}
	return toSerialize, nil
}

type NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner struct {
	value *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner
	isSet bool
}

func (v NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) Get() *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner {
	return v.value
}

func (v *NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) Set(val *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner(val *ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) *NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner {
	return &NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner{value: val, isSet: true}
}

func (v NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


