/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the IdentityStore201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityStore201ResponseData{}

// IdentityStore201ResponseData struct for IdentityStore201ResponseData
type IdentityStore201ResponseData struct {
	Id *int32 `json:"id,omitempty"`
}

// NewIdentityStore201ResponseData instantiates a new IdentityStore201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityStore201ResponseData() *IdentityStore201ResponseData {
	this := IdentityStore201ResponseData{}
	return &this
}

// NewIdentityStore201ResponseDataWithDefaults instantiates a new IdentityStore201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityStore201ResponseDataWithDefaults() *IdentityStore201ResponseData {
	this := IdentityStore201ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IdentityStore201ResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityStore201ResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IdentityStore201ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IdentityStore201ResponseData) SetId(v int32) {
	o.Id = &v
}

func (o IdentityStore201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityStore201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableIdentityStore201ResponseData struct {
	value *IdentityStore201ResponseData
	isSet bool
}

func (v NullableIdentityStore201ResponseData) Get() *IdentityStore201ResponseData {
	return v.value
}

func (v *NullableIdentityStore201ResponseData) Set(val *IdentityStore201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityStore201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityStore201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityStore201ResponseData(val *IdentityStore201ResponseData) *NullableIdentityStore201ResponseData {
	return &NullableIdentityStore201ResponseData{value: val, isSet: true}
}

func (v NullableIdentityStore201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityStore201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


