/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the RegistryHasAccreditation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistryHasAccreditation{}

// RegistryHasAccreditation Pivot model representing the relationship between registries and accreditations
type RegistryHasAccreditation struct {
	// ID of the registry
	RegistryId *int32 `json:"registry_id,omitempty"`
	// ID of the accreditation
	AccreditationId *int32 `json:"accreditation_id,omitempty"`
}

// NewRegistryHasAccreditation instantiates a new RegistryHasAccreditation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryHasAccreditation() *RegistryHasAccreditation {
	this := RegistryHasAccreditation{}
	return &this
}

// NewRegistryHasAccreditationWithDefaults instantiates a new RegistryHasAccreditation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryHasAccreditationWithDefaults() *RegistryHasAccreditation {
	this := RegistryHasAccreditation{}
	return &this
}

// GetRegistryId returns the RegistryId field value if set, zero value otherwise.
func (o *RegistryHasAccreditation) GetRegistryId() int32 {
	if o == nil || IsNil(o.RegistryId) {
		var ret int32
		return ret
	}
	return *o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryHasAccreditation) GetRegistryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistryId) {
		return nil, false
	}
	return o.RegistryId, true
}

// HasRegistryId returns a boolean if a field has been set.
func (o *RegistryHasAccreditation) HasRegistryId() bool {
	if o != nil && !IsNil(o.RegistryId) {
		return true
	}

	return false
}

// SetRegistryId gets a reference to the given int32 and assigns it to the RegistryId field.
func (o *RegistryHasAccreditation) SetRegistryId(v int32) {
	o.RegistryId = &v
}

// GetAccreditationId returns the AccreditationId field value if set, zero value otherwise.
func (o *RegistryHasAccreditation) GetAccreditationId() int32 {
	if o == nil || IsNil(o.AccreditationId) {
		var ret int32
		return ret
	}
	return *o.AccreditationId
}

// GetAccreditationIdOk returns a tuple with the AccreditationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryHasAccreditation) GetAccreditationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccreditationId) {
		return nil, false
	}
	return o.AccreditationId, true
}

// HasAccreditationId returns a boolean if a field has been set.
func (o *RegistryHasAccreditation) HasAccreditationId() bool {
	if o != nil && !IsNil(o.AccreditationId) {
		return true
	}

	return false
}

// SetAccreditationId gets a reference to the given int32 and assigns it to the AccreditationId field.
func (o *RegistryHasAccreditation) SetAccreditationId(v int32) {
	o.AccreditationId = &v
}

func (o RegistryHasAccreditation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistryHasAccreditation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RegistryId) {
		toSerialize["registry_id"] = o.RegistryId
	}
	if !IsNil(o.AccreditationId) {
		toSerialize["accreditation_id"] = o.AccreditationId
	}
	return toSerialize, nil
}

type NullableRegistryHasAccreditation struct {
	value *RegistryHasAccreditation
	isSet bool
}

func (v NullableRegistryHasAccreditation) Get() *RegistryHasAccreditation {
	return v.value
}

func (v *NullableRegistryHasAccreditation) Set(val *RegistryHasAccreditation) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryHasAccreditation) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryHasAccreditation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryHasAccreditation(val *RegistryHasAccreditation) *NullableRegistryHasAccreditation {
	return &NullableRegistryHasAccreditation{value: val, isSet: true}
}

func (v NullableRegistryHasAccreditation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryHasAccreditation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


