/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the ProjectDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectDetail{}

// ProjectDetail ProjectDetail model
type ProjectDetail struct {
	// Model primary key
	Id *int32 `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Primary key of associated Project for this ProjectDetail
	ProjectId *int32 `json:"project_id,omitempty"`
	Datasets []string `json:"datasets,omitempty"`
	OtherApprovalCommittees []string `json:"other_approval_committees,omitempty"`
	DataSensitivityLevel *string `json:"data_sensitivity_level,omitempty"`
	LegalBasisForDataArticle6 *string `json:"legal_basis_for_data_article6,omitempty"`
	DutyOfConfidentiality *bool `json:"duty_of_confidentiality,omitempty"`
	NationalDataOptout *bool `json:"national_data_optout,omitempty"`
	RequestFrequency *string `json:"request_frequency,omitempty"`
	DatasetLinkageDescription *string `json:"dataset_linkage_description,omitempty"`
	DataMinimisation *string `json:"data_minimisation,omitempty"`
	DataUseDescription *string `json:"data_use_description,omitempty"`
	AccessDate *string `json:"access_date,omitempty"`
	AccessType *int32 `json:"access_type,omitempty"`
	DataPrivacy *string `json:"data_privacy,omitempty"`
	ResearchOutputs map[string]interface{} `json:"research_outputs,omitempty"`
	DataAssets *string `json:"data_assets,omitempty"`
}

// NewProjectDetail instantiates a new ProjectDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectDetail() *ProjectDetail {
	this := ProjectDetail{}
	return &this
}

// NewProjectDetailWithDefaults instantiates a new ProjectDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectDetailWithDefaults() *ProjectDetail {
	this := ProjectDetail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectDetail) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectDetail) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProjectDetail) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectDetail) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectDetail) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ProjectDetail) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectDetail) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectDetail) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ProjectDetail) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ProjectDetail) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectDetail) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *ProjectDetail) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetDatasets returns the Datasets field value if set, zero value otherwise.
func (o *ProjectDetail) GetDatasets() []string {
	if o == nil || IsNil(o.Datasets) {
		var ret []string
		return ret
	}
	return o.Datasets
}

// GetDatasetsOk returns a tuple with the Datasets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDatasetsOk() ([]string, bool) {
	if o == nil || IsNil(o.Datasets) {
		return nil, false
	}
	return o.Datasets, true
}

// HasDatasets returns a boolean if a field has been set.
func (o *ProjectDetail) HasDatasets() bool {
	if o != nil && !IsNil(o.Datasets) {
		return true
	}

	return false
}

// SetDatasets gets a reference to the given []string and assigns it to the Datasets field.
func (o *ProjectDetail) SetDatasets(v []string) {
	o.Datasets = v
}

// GetOtherApprovalCommittees returns the OtherApprovalCommittees field value if set, zero value otherwise.
func (o *ProjectDetail) GetOtherApprovalCommittees() []string {
	if o == nil || IsNil(o.OtherApprovalCommittees) {
		var ret []string
		return ret
	}
	return o.OtherApprovalCommittees
}

// GetOtherApprovalCommitteesOk returns a tuple with the OtherApprovalCommittees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetOtherApprovalCommitteesOk() ([]string, bool) {
	if o == nil || IsNil(o.OtherApprovalCommittees) {
		return nil, false
	}
	return o.OtherApprovalCommittees, true
}

// HasOtherApprovalCommittees returns a boolean if a field has been set.
func (o *ProjectDetail) HasOtherApprovalCommittees() bool {
	if o != nil && !IsNil(o.OtherApprovalCommittees) {
		return true
	}

	return false
}

// SetOtherApprovalCommittees gets a reference to the given []string and assigns it to the OtherApprovalCommittees field.
func (o *ProjectDetail) SetOtherApprovalCommittees(v []string) {
	o.OtherApprovalCommittees = v
}

// GetDataSensitivityLevel returns the DataSensitivityLevel field value if set, zero value otherwise.
func (o *ProjectDetail) GetDataSensitivityLevel() string {
	if o == nil || IsNil(o.DataSensitivityLevel) {
		var ret string
		return ret
	}
	return *o.DataSensitivityLevel
}

// GetDataSensitivityLevelOk returns a tuple with the DataSensitivityLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDataSensitivityLevelOk() (*string, bool) {
	if o == nil || IsNil(o.DataSensitivityLevel) {
		return nil, false
	}
	return o.DataSensitivityLevel, true
}

// HasDataSensitivityLevel returns a boolean if a field has been set.
func (o *ProjectDetail) HasDataSensitivityLevel() bool {
	if o != nil && !IsNil(o.DataSensitivityLevel) {
		return true
	}

	return false
}

// SetDataSensitivityLevel gets a reference to the given string and assigns it to the DataSensitivityLevel field.
func (o *ProjectDetail) SetDataSensitivityLevel(v string) {
	o.DataSensitivityLevel = &v
}

// GetLegalBasisForDataArticle6 returns the LegalBasisForDataArticle6 field value if set, zero value otherwise.
func (o *ProjectDetail) GetLegalBasisForDataArticle6() string {
	if o == nil || IsNil(o.LegalBasisForDataArticle6) {
		var ret string
		return ret
	}
	return *o.LegalBasisForDataArticle6
}

// GetLegalBasisForDataArticle6Ok returns a tuple with the LegalBasisForDataArticle6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetLegalBasisForDataArticle6Ok() (*string, bool) {
	if o == nil || IsNil(o.LegalBasisForDataArticle6) {
		return nil, false
	}
	return o.LegalBasisForDataArticle6, true
}

// HasLegalBasisForDataArticle6 returns a boolean if a field has been set.
func (o *ProjectDetail) HasLegalBasisForDataArticle6() bool {
	if o != nil && !IsNil(o.LegalBasisForDataArticle6) {
		return true
	}

	return false
}

// SetLegalBasisForDataArticle6 gets a reference to the given string and assigns it to the LegalBasisForDataArticle6 field.
func (o *ProjectDetail) SetLegalBasisForDataArticle6(v string) {
	o.LegalBasisForDataArticle6 = &v
}

// GetDutyOfConfidentiality returns the DutyOfConfidentiality field value if set, zero value otherwise.
func (o *ProjectDetail) GetDutyOfConfidentiality() bool {
	if o == nil || IsNil(o.DutyOfConfidentiality) {
		var ret bool
		return ret
	}
	return *o.DutyOfConfidentiality
}

// GetDutyOfConfidentialityOk returns a tuple with the DutyOfConfidentiality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDutyOfConfidentialityOk() (*bool, bool) {
	if o == nil || IsNil(o.DutyOfConfidentiality) {
		return nil, false
	}
	return o.DutyOfConfidentiality, true
}

// HasDutyOfConfidentiality returns a boolean if a field has been set.
func (o *ProjectDetail) HasDutyOfConfidentiality() bool {
	if o != nil && !IsNil(o.DutyOfConfidentiality) {
		return true
	}

	return false
}

// SetDutyOfConfidentiality gets a reference to the given bool and assigns it to the DutyOfConfidentiality field.
func (o *ProjectDetail) SetDutyOfConfidentiality(v bool) {
	o.DutyOfConfidentiality = &v
}

// GetNationalDataOptout returns the NationalDataOptout field value if set, zero value otherwise.
func (o *ProjectDetail) GetNationalDataOptout() bool {
	if o == nil || IsNil(o.NationalDataOptout) {
		var ret bool
		return ret
	}
	return *o.NationalDataOptout
}

// GetNationalDataOptoutOk returns a tuple with the NationalDataOptout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetNationalDataOptoutOk() (*bool, bool) {
	if o == nil || IsNil(o.NationalDataOptout) {
		return nil, false
	}
	return o.NationalDataOptout, true
}

// HasNationalDataOptout returns a boolean if a field has been set.
func (o *ProjectDetail) HasNationalDataOptout() bool {
	if o != nil && !IsNil(o.NationalDataOptout) {
		return true
	}

	return false
}

// SetNationalDataOptout gets a reference to the given bool and assigns it to the NationalDataOptout field.
func (o *ProjectDetail) SetNationalDataOptout(v bool) {
	o.NationalDataOptout = &v
}

// GetRequestFrequency returns the RequestFrequency field value if set, zero value otherwise.
func (o *ProjectDetail) GetRequestFrequency() string {
	if o == nil || IsNil(o.RequestFrequency) {
		var ret string
		return ret
	}
	return *o.RequestFrequency
}

// GetRequestFrequencyOk returns a tuple with the RequestFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetRequestFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.RequestFrequency) {
		return nil, false
	}
	return o.RequestFrequency, true
}

// HasRequestFrequency returns a boolean if a field has been set.
func (o *ProjectDetail) HasRequestFrequency() bool {
	if o != nil && !IsNil(o.RequestFrequency) {
		return true
	}

	return false
}

// SetRequestFrequency gets a reference to the given string and assigns it to the RequestFrequency field.
func (o *ProjectDetail) SetRequestFrequency(v string) {
	o.RequestFrequency = &v
}

// GetDatasetLinkageDescription returns the DatasetLinkageDescription field value if set, zero value otherwise.
func (o *ProjectDetail) GetDatasetLinkageDescription() string {
	if o == nil || IsNil(o.DatasetLinkageDescription) {
		var ret string
		return ret
	}
	return *o.DatasetLinkageDescription
}

// GetDatasetLinkageDescriptionOk returns a tuple with the DatasetLinkageDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDatasetLinkageDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DatasetLinkageDescription) {
		return nil, false
	}
	return o.DatasetLinkageDescription, true
}

// HasDatasetLinkageDescription returns a boolean if a field has been set.
func (o *ProjectDetail) HasDatasetLinkageDescription() bool {
	if o != nil && !IsNil(o.DatasetLinkageDescription) {
		return true
	}

	return false
}

// SetDatasetLinkageDescription gets a reference to the given string and assigns it to the DatasetLinkageDescription field.
func (o *ProjectDetail) SetDatasetLinkageDescription(v string) {
	o.DatasetLinkageDescription = &v
}

// GetDataMinimisation returns the DataMinimisation field value if set, zero value otherwise.
func (o *ProjectDetail) GetDataMinimisation() string {
	if o == nil || IsNil(o.DataMinimisation) {
		var ret string
		return ret
	}
	return *o.DataMinimisation
}

// GetDataMinimisationOk returns a tuple with the DataMinimisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDataMinimisationOk() (*string, bool) {
	if o == nil || IsNil(o.DataMinimisation) {
		return nil, false
	}
	return o.DataMinimisation, true
}

// HasDataMinimisation returns a boolean if a field has been set.
func (o *ProjectDetail) HasDataMinimisation() bool {
	if o != nil && !IsNil(o.DataMinimisation) {
		return true
	}

	return false
}

// SetDataMinimisation gets a reference to the given string and assigns it to the DataMinimisation field.
func (o *ProjectDetail) SetDataMinimisation(v string) {
	o.DataMinimisation = &v
}

// GetDataUseDescription returns the DataUseDescription field value if set, zero value otherwise.
func (o *ProjectDetail) GetDataUseDescription() string {
	if o == nil || IsNil(o.DataUseDescription) {
		var ret string
		return ret
	}
	return *o.DataUseDescription
}

// GetDataUseDescriptionOk returns a tuple with the DataUseDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDataUseDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DataUseDescription) {
		return nil, false
	}
	return o.DataUseDescription, true
}

// HasDataUseDescription returns a boolean if a field has been set.
func (o *ProjectDetail) HasDataUseDescription() bool {
	if o != nil && !IsNil(o.DataUseDescription) {
		return true
	}

	return false
}

// SetDataUseDescription gets a reference to the given string and assigns it to the DataUseDescription field.
func (o *ProjectDetail) SetDataUseDescription(v string) {
	o.DataUseDescription = &v
}

// GetAccessDate returns the AccessDate field value if set, zero value otherwise.
func (o *ProjectDetail) GetAccessDate() string {
	if o == nil || IsNil(o.AccessDate) {
		var ret string
		return ret
	}
	return *o.AccessDate
}

// GetAccessDateOk returns a tuple with the AccessDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetAccessDateOk() (*string, bool) {
	if o == nil || IsNil(o.AccessDate) {
		return nil, false
	}
	return o.AccessDate, true
}

// HasAccessDate returns a boolean if a field has been set.
func (o *ProjectDetail) HasAccessDate() bool {
	if o != nil && !IsNil(o.AccessDate) {
		return true
	}

	return false
}

// SetAccessDate gets a reference to the given string and assigns it to the AccessDate field.
func (o *ProjectDetail) SetAccessDate(v string) {
	o.AccessDate = &v
}

// GetAccessType returns the AccessType field value if set, zero value otherwise.
func (o *ProjectDetail) GetAccessType() int32 {
	if o == nil || IsNil(o.AccessType) {
		var ret int32
		return ret
	}
	return *o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetAccessTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.AccessType) {
		return nil, false
	}
	return o.AccessType, true
}

// HasAccessType returns a boolean if a field has been set.
func (o *ProjectDetail) HasAccessType() bool {
	if o != nil && !IsNil(o.AccessType) {
		return true
	}

	return false
}

// SetAccessType gets a reference to the given int32 and assigns it to the AccessType field.
func (o *ProjectDetail) SetAccessType(v int32) {
	o.AccessType = &v
}

// GetDataPrivacy returns the DataPrivacy field value if set, zero value otherwise.
func (o *ProjectDetail) GetDataPrivacy() string {
	if o == nil || IsNil(o.DataPrivacy) {
		var ret string
		return ret
	}
	return *o.DataPrivacy
}

// GetDataPrivacyOk returns a tuple with the DataPrivacy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDataPrivacyOk() (*string, bool) {
	if o == nil || IsNil(o.DataPrivacy) {
		return nil, false
	}
	return o.DataPrivacy, true
}

// HasDataPrivacy returns a boolean if a field has been set.
func (o *ProjectDetail) HasDataPrivacy() bool {
	if o != nil && !IsNil(o.DataPrivacy) {
		return true
	}

	return false
}

// SetDataPrivacy gets a reference to the given string and assigns it to the DataPrivacy field.
func (o *ProjectDetail) SetDataPrivacy(v string) {
	o.DataPrivacy = &v
}

// GetResearchOutputs returns the ResearchOutputs field value if set, zero value otherwise.
func (o *ProjectDetail) GetResearchOutputs() map[string]interface{} {
	if o == nil || IsNil(o.ResearchOutputs) {
		var ret map[string]interface{}
		return ret
	}
	return o.ResearchOutputs
}

// GetResearchOutputsOk returns a tuple with the ResearchOutputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetResearchOutputsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResearchOutputs) {
		return map[string]interface{}{}, false
	}
	return o.ResearchOutputs, true
}

// HasResearchOutputs returns a boolean if a field has been set.
func (o *ProjectDetail) HasResearchOutputs() bool {
	if o != nil && !IsNil(o.ResearchOutputs) {
		return true
	}

	return false
}

// SetResearchOutputs gets a reference to the given map[string]interface{} and assigns it to the ResearchOutputs field.
func (o *ProjectDetail) SetResearchOutputs(v map[string]interface{}) {
	o.ResearchOutputs = v
}

// GetDataAssets returns the DataAssets field value if set, zero value otherwise.
func (o *ProjectDetail) GetDataAssets() string {
	if o == nil || IsNil(o.DataAssets) {
		var ret string
		return ret
	}
	return *o.DataAssets
}

// GetDataAssetsOk returns a tuple with the DataAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDetail) GetDataAssetsOk() (*string, bool) {
	if o == nil || IsNil(o.DataAssets) {
		return nil, false
	}
	return o.DataAssets, true
}

// HasDataAssets returns a boolean if a field has been set.
func (o *ProjectDetail) HasDataAssets() bool {
	if o != nil && !IsNil(o.DataAssets) {
		return true
	}

	return false
}

// SetDataAssets gets a reference to the given string and assigns it to the DataAssets field.
func (o *ProjectDetail) SetDataAssets(v string) {
	o.DataAssets = &v
}

func (o ProjectDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Datasets) {
		toSerialize["datasets"] = o.Datasets
	}
	if !IsNil(o.OtherApprovalCommittees) {
		toSerialize["other_approval_committees"] = o.OtherApprovalCommittees
	}
	if !IsNil(o.DataSensitivityLevel) {
		toSerialize["data_sensitivity_level"] = o.DataSensitivityLevel
	}
	if !IsNil(o.LegalBasisForDataArticle6) {
		toSerialize["legal_basis_for_data_article6"] = o.LegalBasisForDataArticle6
	}
	if !IsNil(o.DutyOfConfidentiality) {
		toSerialize["duty_of_confidentiality"] = o.DutyOfConfidentiality
	}
	if !IsNil(o.NationalDataOptout) {
		toSerialize["national_data_optout"] = o.NationalDataOptout
	}
	if !IsNil(o.RequestFrequency) {
		toSerialize["request_frequency"] = o.RequestFrequency
	}
	if !IsNil(o.DatasetLinkageDescription) {
		toSerialize["dataset_linkage_description"] = o.DatasetLinkageDescription
	}
	if !IsNil(o.DataMinimisation) {
		toSerialize["data_minimisation"] = o.DataMinimisation
	}
	if !IsNil(o.DataUseDescription) {
		toSerialize["data_use_description"] = o.DataUseDescription
	}
	if !IsNil(o.AccessDate) {
		toSerialize["access_date"] = o.AccessDate
	}
	if !IsNil(o.AccessType) {
		toSerialize["access_type"] = o.AccessType
	}
	if !IsNil(o.DataPrivacy) {
		toSerialize["data_privacy"] = o.DataPrivacy
	}
	if !IsNil(o.ResearchOutputs) {
		toSerialize["research_outputs"] = o.ResearchOutputs
	}
	if !IsNil(o.DataAssets) {
		toSerialize["data_assets"] = o.DataAssets
	}
	return toSerialize, nil
}

type NullableProjectDetail struct {
	value *ProjectDetail
	isSet bool
}

func (v NullableProjectDetail) Get() *ProjectDetail {
	return v.value
}

func (v *NullableProjectDetail) Set(val *ProjectDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectDetail(val *ProjectDetail) *NullableProjectDetail {
	return &NullableProjectDetail{value: val, isSet: true}
}

func (v NullableProjectDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


