/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the AccreditationStoreByRegistryId201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccreditationStoreByRegistryId201Response{}

// AccreditationStoreByRegistryId201Response struct for AccreditationStoreByRegistryId201Response
type AccreditationStoreByRegistryId201Response struct {
	Message *string `json:"message,omitempty"`
	Data *int32 `json:"data,omitempty"`
}

// NewAccreditationStoreByRegistryId201Response instantiates a new AccreditationStoreByRegistryId201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccreditationStoreByRegistryId201Response() *AccreditationStoreByRegistryId201Response {
	this := AccreditationStoreByRegistryId201Response{}
	return &this
}

// NewAccreditationStoreByRegistryId201ResponseWithDefaults instantiates a new AccreditationStoreByRegistryId201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccreditationStoreByRegistryId201ResponseWithDefaults() *AccreditationStoreByRegistryId201Response {
	this := AccreditationStoreByRegistryId201Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AccreditationStoreByRegistryId201Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccreditationStoreByRegistryId201Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AccreditationStoreByRegistryId201Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AccreditationStoreByRegistryId201Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AccreditationStoreByRegistryId201Response) GetData() int32 {
	if o == nil || IsNil(o.Data) {
		var ret int32
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccreditationStoreByRegistryId201Response) GetDataOk() (*int32, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AccreditationStoreByRegistryId201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given int32 and assigns it to the Data field.
func (o *AccreditationStoreByRegistryId201Response) SetData(v int32) {
	o.Data = &v
}

func (o AccreditationStoreByRegistryId201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccreditationStoreByRegistryId201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAccreditationStoreByRegistryId201Response struct {
	value *AccreditationStoreByRegistryId201Response
	isSet bool
}

func (v NullableAccreditationStoreByRegistryId201Response) Get() *AccreditationStoreByRegistryId201Response {
	return v.value
}

func (v *NullableAccreditationStoreByRegistryId201Response) Set(val *AccreditationStoreByRegistryId201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAccreditationStoreByRegistryId201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAccreditationStoreByRegistryId201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccreditationStoreByRegistryId201Response(val *AccreditationStoreByRegistryId201Response) *NullableAccreditationStoreByRegistryId201Response {
	return &NullableAccreditationStoreByRegistryId201Response{value: val, isSet: true}
}

func (v NullableAccreditationStoreByRegistryId201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccreditationStoreByRegistryId201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


