/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustodiansCreateCustodianValidationChecksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodiansCreateCustodianValidationChecksRequest{}

// CustodiansCreateCustodianValidationChecksRequest struct for CustodiansCreateCustodianValidationChecksRequest
type CustodiansCreateCustodianValidationChecksRequest struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Description *string `json:"description,omitempty"`
}

type _CustodiansCreateCustodianValidationChecksRequest CustodiansCreateCustodianValidationChecksRequest

// NewCustodiansCreateCustodianValidationChecksRequest instantiates a new CustodiansCreateCustodianValidationChecksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodiansCreateCustodianValidationChecksRequest(name string, type_ string) *CustodiansCreateCustodianValidationChecksRequest {
	this := CustodiansCreateCustodianValidationChecksRequest{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewCustodiansCreateCustodianValidationChecksRequestWithDefaults instantiates a new CustodiansCreateCustodianValidationChecksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodiansCreateCustodianValidationChecksRequestWithDefaults() *CustodiansCreateCustodianValidationChecksRequest {
	this := CustodiansCreateCustodianValidationChecksRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CustodiansCreateCustodianValidationChecksRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustodiansCreateCustodianValidationChecksRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustodiansCreateCustodianValidationChecksRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CustodiansCreateCustodianValidationChecksRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CustodiansCreateCustodianValidationChecksRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CustodiansCreateCustodianValidationChecksRequest) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustodiansCreateCustodianValidationChecksRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodiansCreateCustodianValidationChecksRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustodiansCreateCustodianValidationChecksRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustodiansCreateCustodianValidationChecksRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CustodiansCreateCustodianValidationChecksRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodiansCreateCustodianValidationChecksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *CustodiansCreateCustodianValidationChecksRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustodiansCreateCustodianValidationChecksRequest := _CustodiansCreateCustodianValidationChecksRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustodiansCreateCustodianValidationChecksRequest)

	if err != nil {
		return err
	}

	*o = CustodiansCreateCustodianValidationChecksRequest(varCustodiansCreateCustodianValidationChecksRequest)

	return err
}

type NullableCustodiansCreateCustodianValidationChecksRequest struct {
	value *CustodiansCreateCustodianValidationChecksRequest
	isSet bool
}

func (v NullableCustodiansCreateCustodianValidationChecksRequest) Get() *CustodiansCreateCustodianValidationChecksRequest {
	return v.value
}

func (v *NullableCustodiansCreateCustodianValidationChecksRequest) Set(val *CustodiansCreateCustodianValidationChecksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodiansCreateCustodianValidationChecksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodiansCreateCustodianValidationChecksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodiansCreateCustodianValidationChecksRequest(val *CustodiansCreateCustodianValidationChecksRequest) *NullableCustodiansCreateCustodianValidationChecksRequest {
	return &NullableCustodiansCreateCustodianValidationChecksRequest{value: val, isSet: true}
}

func (v NullableCustodiansCreateCustodianValidationChecksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodiansCreateCustodianValidationChecksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


