/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the ProjectStoreRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectStoreRequest{}

// ProjectStoreRequest struct for ProjectStoreRequest
type ProjectStoreRequest struct {
	RegistryId *int32 `json:"registry_id,omitempty"`
	Name *string `json:"name,omitempty"`
	PublicBenefit *string `json:"public_benefit,omitempty"`
	RunsTo *string `json:"runs_to,omitempty"`
}

// NewProjectStoreRequest instantiates a new ProjectStoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectStoreRequest() *ProjectStoreRequest {
	this := ProjectStoreRequest{}
	return &this
}

// NewProjectStoreRequestWithDefaults instantiates a new ProjectStoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectStoreRequestWithDefaults() *ProjectStoreRequest {
	this := ProjectStoreRequest{}
	return &this
}

// GetRegistryId returns the RegistryId field value if set, zero value otherwise.
func (o *ProjectStoreRequest) GetRegistryId() int32 {
	if o == nil || IsNil(o.RegistryId) {
		var ret int32
		return ret
	}
	return *o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStoreRequest) GetRegistryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistryId) {
		return nil, false
	}
	return o.RegistryId, true
}

// HasRegistryId returns a boolean if a field has been set.
func (o *ProjectStoreRequest) HasRegistryId() bool {
	if o != nil && !IsNil(o.RegistryId) {
		return true
	}

	return false
}

// SetRegistryId gets a reference to the given int32 and assigns it to the RegistryId field.
func (o *ProjectStoreRequest) SetRegistryId(v int32) {
	o.RegistryId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectStoreRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStoreRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectStoreRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectStoreRequest) SetName(v string) {
	o.Name = &v
}

// GetPublicBenefit returns the PublicBenefit field value if set, zero value otherwise.
func (o *ProjectStoreRequest) GetPublicBenefit() string {
	if o == nil || IsNil(o.PublicBenefit) {
		var ret string
		return ret
	}
	return *o.PublicBenefit
}

// GetPublicBenefitOk returns a tuple with the PublicBenefit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStoreRequest) GetPublicBenefitOk() (*string, bool) {
	if o == nil || IsNil(o.PublicBenefit) {
		return nil, false
	}
	return o.PublicBenefit, true
}

// HasPublicBenefit returns a boolean if a field has been set.
func (o *ProjectStoreRequest) HasPublicBenefit() bool {
	if o != nil && !IsNil(o.PublicBenefit) {
		return true
	}

	return false
}

// SetPublicBenefit gets a reference to the given string and assigns it to the PublicBenefit field.
func (o *ProjectStoreRequest) SetPublicBenefit(v string) {
	o.PublicBenefit = &v
}

// GetRunsTo returns the RunsTo field value if set, zero value otherwise.
func (o *ProjectStoreRequest) GetRunsTo() string {
	if o == nil || IsNil(o.RunsTo) {
		var ret string
		return ret
	}
	return *o.RunsTo
}

// GetRunsToOk returns a tuple with the RunsTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectStoreRequest) GetRunsToOk() (*string, bool) {
	if o == nil || IsNil(o.RunsTo) {
		return nil, false
	}
	return o.RunsTo, true
}

// HasRunsTo returns a boolean if a field has been set.
func (o *ProjectStoreRequest) HasRunsTo() bool {
	if o != nil && !IsNil(o.RunsTo) {
		return true
	}

	return false
}

// SetRunsTo gets a reference to the given string and assigns it to the RunsTo field.
func (o *ProjectStoreRequest) SetRunsTo(v string) {
	o.RunsTo = &v
}

func (o ProjectStoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectStoreRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RegistryId) {
		toSerialize["registry_id"] = o.RegistryId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PublicBenefit) {
		toSerialize["public_benefit"] = o.PublicBenefit
	}
	if !IsNil(o.RunsTo) {
		toSerialize["runs_to"] = o.RunsTo
	}
	return toSerialize, nil
}

type NullableProjectStoreRequest struct {
	value *ProjectStoreRequest
	isSet bool
}

func (v NullableProjectStoreRequest) Get() *ProjectStoreRequest {
	return v.value
}

func (v *NullableProjectStoreRequest) Set(val *ProjectStoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectStoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectStoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectStoreRequest(val *ProjectStoreRequest) *NullableProjectStoreRequest {
	return &NullableProjectStoreRequest{value: val, isSet: true}
}

func (v NullableProjectStoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectStoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


