/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
	"time"
)

// checks if the IDVTPlugin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IDVTPlugin{}

// IDVTPlugin Model representing IDVT plugins
type IDVTPlugin struct {
	// Unique identifier for the IDVT plugin
	Id *int32 `json:"id,omitempty"`
	// Function name of the plugin
	Function *string `json:"function,omitempty"`
	// Arguments passed to the plugin function
	Args *string `json:"args,omitempty"`
	// Configuration settings for the plugin
	Config *string `json:"config,omitempty"`
	// Indicates whether the plugin is enabled (1 for enabled, 0 for disabled)
	Enabled *int32 `json:"enabled,omitempty"`
	// Timestamp when the plugin was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Timestamp when the plugin was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewIDVTPlugin instantiates a new IDVTPlugin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIDVTPlugin() *IDVTPlugin {
	this := IDVTPlugin{}
	return &this
}

// NewIDVTPluginWithDefaults instantiates a new IDVTPlugin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIDVTPluginWithDefaults() *IDVTPlugin {
	this := IDVTPlugin{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IDVTPlugin) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IDVTPlugin) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IDVTPlugin) SetId(v int32) {
	o.Id = &v
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (o *IDVTPlugin) GetFunction() string {
	if o == nil || IsNil(o.Function) {
		var ret string
		return ret
	}
	return *o.Function
}

// GetFunctionOk returns a tuple with the Function field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetFunctionOk() (*string, bool) {
	if o == nil || IsNil(o.Function) {
		return nil, false
	}
	return o.Function, true
}

// HasFunction returns a boolean if a field has been set.
func (o *IDVTPlugin) HasFunction() bool {
	if o != nil && !IsNil(o.Function) {
		return true
	}

	return false
}

// SetFunction gets a reference to the given string and assigns it to the Function field.
func (o *IDVTPlugin) SetFunction(v string) {
	o.Function = &v
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *IDVTPlugin) GetArgs() string {
	if o == nil || IsNil(o.Args) {
		var ret string
		return ret
	}
	return *o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetArgsOk() (*string, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *IDVTPlugin) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given string and assigns it to the Args field.
func (o *IDVTPlugin) SetArgs(v string) {
	o.Args = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *IDVTPlugin) GetConfig() string {
	if o == nil || IsNil(o.Config) {
		var ret string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetConfigOk() (*string, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *IDVTPlugin) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given string and assigns it to the Config field.
func (o *IDVTPlugin) SetConfig(v string) {
	o.Config = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *IDVTPlugin) GetEnabled() int32 {
	if o == nil || IsNil(o.Enabled) {
		var ret int32
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetEnabledOk() (*int32, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *IDVTPlugin) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given int32 and assigns it to the Enabled field.
func (o *IDVTPlugin) SetEnabled(v int32) {
	o.Enabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *IDVTPlugin) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *IDVTPlugin) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *IDVTPlugin) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IDVTPlugin) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IDVTPlugin) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IDVTPlugin) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IDVTPlugin) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o IDVTPlugin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IDVTPlugin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Function) {
		toSerialize["function"] = o.Function
	}
	if !IsNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableIDVTPlugin struct {
	value *IDVTPlugin
	isSet bool
}

func (v NullableIDVTPlugin) Get() *IDVTPlugin {
	return v.value
}

func (v *NullableIDVTPlugin) Set(val *IDVTPlugin) {
	v.value = val
	v.isSet = true
}

func (v NullableIDVTPlugin) IsSet() bool {
	return v.isSet
}

func (v *NullableIDVTPlugin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIDVTPlugin(val *IDVTPlugin) *NullableIDVTPlugin {
	return &NullableIDVTPlugin{value: val, isSet: true}
}

func (v NullableIDVTPlugin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIDVTPlugin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


