/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the CustodianUsersIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodianUsersIndex200Response{}

// CustodianUsersIndex200Response struct for CustodianUsersIndex200Response
type CustodianUsersIndex200Response struct {
	Message *string `json:"message,omitempty"`
	Data *CustodianUser `json:"data,omitempty"`
}

// NewCustodianUsersIndex200Response instantiates a new CustodianUsersIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodianUsersIndex200Response() *CustodianUsersIndex200Response {
	this := CustodianUsersIndex200Response{}
	return &this
}

// NewCustodianUsersIndex200ResponseWithDefaults instantiates a new CustodianUsersIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodianUsersIndex200ResponseWithDefaults() *CustodianUsersIndex200Response {
	this := CustodianUsersIndex200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CustodianUsersIndex200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUsersIndex200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CustodianUsersIndex200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CustodianUsersIndex200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustodianUsersIndex200Response) GetData() CustodianUser {
	if o == nil || IsNil(o.Data) {
		var ret CustodianUser
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianUsersIndex200Response) GetDataOk() (*CustodianUser, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustodianUsersIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CustodianUser and assigns it to the Data field.
func (o *CustodianUsersIndex200Response) SetData(v CustodianUser) {
	o.Data = &v
}

func (o CustodianUsersIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodianUsersIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCustodianUsersIndex200Response struct {
	value *CustodianUsersIndex200Response
	isSet bool
}

func (v NullableCustodianUsersIndex200Response) Get() *CustodianUsersIndex200Response {
	return v.value
}

func (v *NullableCustodianUsersIndex200Response) Set(val *CustodianUsersIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianUsersIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianUsersIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianUsersIndex200Response(val *CustodianUsersIndex200Response) *NullableCustodianUsersIndex200Response {
	return &NullableCustodianUsersIndex200Response{value: val, isSet: true}
}

func (v NullableCustodianUsersIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianUsersIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


