/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the OrganisationsGetRegistries200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganisationsGetRegistries200ResponseData{}

// OrganisationsGetRegistries200ResponseData struct for OrganisationsGetRegistries200ResponseData
type OrganisationsGetRegistries200ResponseData struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	Data []OrganisationsGetRegistries200ResponseDataDataInner `json:"data,omitempty"`
	FirstPageUrl *string `json:"first_page_url,omitempty"`
	From *int32 `json:"from,omitempty"`
	LastPage *int32 `json:"last_page,omitempty"`
	LastPageUrl *string `json:"last_page_url,omitempty"`
	NextPageUrl *string `json:"next_page_url,omitempty"`
	Path *string `json:"path,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	PrevPageUrl *string `json:"prev_page_url,omitempty"`
	To *int32 `json:"to,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewOrganisationsGetRegistries200ResponseData instantiates a new OrganisationsGetRegistries200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganisationsGetRegistries200ResponseData() *OrganisationsGetRegistries200ResponseData {
	this := OrganisationsGetRegistries200ResponseData{}
	return &this
}

// NewOrganisationsGetRegistries200ResponseDataWithDefaults instantiates a new OrganisationsGetRegistries200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganisationsGetRegistries200ResponseDataWithDefaults() *OrganisationsGetRegistries200ResponseData {
	this := OrganisationsGetRegistries200ResponseData{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *OrganisationsGetRegistries200ResponseData) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetData() []OrganisationsGetRegistries200ResponseDataDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []OrganisationsGetRegistries200ResponseDataDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetDataOk() ([]OrganisationsGetRegistries200ResponseDataDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []OrganisationsGetRegistries200ResponseDataDataInner and assigns it to the Data field.
func (o *OrganisationsGetRegistries200ResponseData) SetData(v []OrganisationsGetRegistries200ResponseDataDataInner) {
	o.Data = v
}

// GetFirstPageUrl returns the FirstPageUrl field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetFirstPageUrl() string {
	if o == nil || IsNil(o.FirstPageUrl) {
		var ret string
		return ret
	}
	return *o.FirstPageUrl
}

// GetFirstPageUrlOk returns a tuple with the FirstPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetFirstPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FirstPageUrl) {
		return nil, false
	}
	return o.FirstPageUrl, true
}

// HasFirstPageUrl returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasFirstPageUrl() bool {
	if o != nil && !IsNil(o.FirstPageUrl) {
		return true
	}

	return false
}

// SetFirstPageUrl gets a reference to the given string and assigns it to the FirstPageUrl field.
func (o *OrganisationsGetRegistries200ResponseData) SetFirstPageUrl(v string) {
	o.FirstPageUrl = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *OrganisationsGetRegistries200ResponseData) SetFrom(v int32) {
	o.From = &v
}

// GetLastPage returns the LastPage field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetLastPage() int32 {
	if o == nil || IsNil(o.LastPage) {
		var ret int32
		return ret
	}
	return *o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetLastPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LastPage) {
		return nil, false
	}
	return o.LastPage, true
}

// HasLastPage returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasLastPage() bool {
	if o != nil && !IsNil(o.LastPage) {
		return true
	}

	return false
}

// SetLastPage gets a reference to the given int32 and assigns it to the LastPage field.
func (o *OrganisationsGetRegistries200ResponseData) SetLastPage(v int32) {
	o.LastPage = &v
}

// GetLastPageUrl returns the LastPageUrl field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetLastPageUrl() string {
	if o == nil || IsNil(o.LastPageUrl) {
		var ret string
		return ret
	}
	return *o.LastPageUrl
}

// GetLastPageUrlOk returns a tuple with the LastPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetLastPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LastPageUrl) {
		return nil, false
	}
	return o.LastPageUrl, true
}

// HasLastPageUrl returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasLastPageUrl() bool {
	if o != nil && !IsNil(o.LastPageUrl) {
		return true
	}

	return false
}

// SetLastPageUrl gets a reference to the given string and assigns it to the LastPageUrl field.
func (o *OrganisationsGetRegistries200ResponseData) SetLastPageUrl(v string) {
	o.LastPageUrl = &v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl) {
		var ret string
		return ret
	}
	return *o.NextPageUrl
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetNextPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageUrl) {
		return nil, false
	}
	return o.NextPageUrl, true
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasNextPageUrl() bool {
	if o != nil && !IsNil(o.NextPageUrl) {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given string and assigns it to the NextPageUrl field.
func (o *OrganisationsGetRegistries200ResponseData) SetNextPageUrl(v string) {
	o.NextPageUrl = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *OrganisationsGetRegistries200ResponseData) SetPath(v string) {
	o.Path = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *OrganisationsGetRegistries200ResponseData) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetPrevPageUrl returns the PrevPageUrl field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetPrevPageUrl() string {
	if o == nil || IsNil(o.PrevPageUrl) {
		var ret string
		return ret
	}
	return *o.PrevPageUrl
}

// GetPrevPageUrlOk returns a tuple with the PrevPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetPrevPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PrevPageUrl) {
		return nil, false
	}
	return o.PrevPageUrl, true
}

// HasPrevPageUrl returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasPrevPageUrl() bool {
	if o != nil && !IsNil(o.PrevPageUrl) {
		return true
	}

	return false
}

// SetPrevPageUrl gets a reference to the given string and assigns it to the PrevPageUrl field.
func (o *OrganisationsGetRegistries200ResponseData) SetPrevPageUrl(v string) {
	o.PrevPageUrl = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetTo() int32 {
	if o == nil || IsNil(o.To) {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetToOk() (*int32, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *OrganisationsGetRegistries200ResponseData) SetTo(v int32) {
	o.To = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *OrganisationsGetRegistries200ResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationsGetRegistries200ResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *OrganisationsGetRegistries200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *OrganisationsGetRegistries200ResponseData) SetTotal(v int32) {
	o.Total = &v
}

func (o OrganisationsGetRegistries200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganisationsGetRegistries200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.FirstPageUrl) {
		toSerialize["first_page_url"] = o.FirstPageUrl
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.LastPage) {
		toSerialize["last_page"] = o.LastPage
	}
	if !IsNil(o.LastPageUrl) {
		toSerialize["last_page_url"] = o.LastPageUrl
	}
	if !IsNil(o.NextPageUrl) {
		toSerialize["next_page_url"] = o.NextPageUrl
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.PrevPageUrl) {
		toSerialize["prev_page_url"] = o.PrevPageUrl
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableOrganisationsGetRegistries200ResponseData struct {
	value *OrganisationsGetRegistries200ResponseData
	isSet bool
}

func (v NullableOrganisationsGetRegistries200ResponseData) Get() *OrganisationsGetRegistries200ResponseData {
	return v.value
}

func (v *NullableOrganisationsGetRegistries200ResponseData) Set(val *OrganisationsGetRegistries200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganisationsGetRegistries200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganisationsGetRegistries200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganisationsGetRegistries200ResponseData(val *OrganisationsGetRegistries200ResponseData) *NullableOrganisationsGetRegistries200ResponseData {
	return &NullableOrganisationsGetRegistries200ResponseData{value: val, isSet: true}
}

func (v NullableOrganisationsGetRegistries200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganisationsGetRegistries200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


