/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the CustodianProjectOrganisationsGetWorkflowStates200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodianProjectOrganisationsGetWorkflowStates200Response{}

// CustodianProjectOrganisationsGetWorkflowStates200Response struct for CustodianProjectOrganisationsGetWorkflowStates200Response
type CustodianProjectOrganisationsGetWorkflowStates200Response struct {
	Message *string `json:"message,omitempty"`
	Data []string `json:"data,omitempty"`
}

// NewCustodianProjectOrganisationsGetWorkflowStates200Response instantiates a new CustodianProjectOrganisationsGetWorkflowStates200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodianProjectOrganisationsGetWorkflowStates200Response() *CustodianProjectOrganisationsGetWorkflowStates200Response {
	this := CustodianProjectOrganisationsGetWorkflowStates200Response{}
	return &this
}

// NewCustodianProjectOrganisationsGetWorkflowStates200ResponseWithDefaults instantiates a new CustodianProjectOrganisationsGetWorkflowStates200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodianProjectOrganisationsGetWorkflowStates200ResponseWithDefaults() *CustodianProjectOrganisationsGetWorkflowStates200Response {
	this := CustodianProjectOrganisationsGetWorkflowStates200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) GetData() []string {
	if o == nil || IsNil(o.Data) {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) GetDataOk() ([]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *CustodianProjectOrganisationsGetWorkflowStates200Response) SetData(v []string) {
	o.Data = v
}

func (o CustodianProjectOrganisationsGetWorkflowStates200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodianProjectOrganisationsGetWorkflowStates200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCustodianProjectOrganisationsGetWorkflowStates200Response struct {
	value *CustodianProjectOrganisationsGetWorkflowStates200Response
	isSet bool
}

func (v NullableCustodianProjectOrganisationsGetWorkflowStates200Response) Get() *CustodianProjectOrganisationsGetWorkflowStates200Response {
	return v.value
}

func (v *NullableCustodianProjectOrganisationsGetWorkflowStates200Response) Set(val *CustodianProjectOrganisationsGetWorkflowStates200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianProjectOrganisationsGetWorkflowStates200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianProjectOrganisationsGetWorkflowStates200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianProjectOrganisationsGetWorkflowStates200Response(val *CustodianProjectOrganisationsGetWorkflowStates200Response) *NullableCustodianProjectOrganisationsGetWorkflowStates200Response {
	return &NullableCustodianProjectOrganisationsGetWorkflowStates200Response{value: val, isSet: true}
}

func (v NullableCustodianProjectOrganisationsGetWorkflowStates200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianProjectOrganisationsGetWorkflowStates200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


