/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the CustodianGetProjectsUsers200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustodianGetProjectsUsers200ResponseData{}

// CustodianGetProjectsUsers200ResponseData struct for CustodianGetProjectsUsers200ResponseData
type CustodianGetProjectsUsers200ResponseData struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Data []CustodianGetProjectsUsers200ResponseDataDataInner `json:"data,omitempty"`
	FirstPageUrl *string `json:"first_page_url,omitempty"`
	LastPageUrl *string `json:"last_page_url,omitempty"`
	NextPageUrl *string `json:"next_page_url,omitempty"`
	PrevPageUrl *string `json:"prev_page_url,omitempty"`
}

// NewCustodianGetProjectsUsers200ResponseData instantiates a new CustodianGetProjectsUsers200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustodianGetProjectsUsers200ResponseData() *CustodianGetProjectsUsers200ResponseData {
	this := CustodianGetProjectsUsers200ResponseData{}
	return &this
}

// NewCustodianGetProjectsUsers200ResponseDataWithDefaults instantiates a new CustodianGetProjectsUsers200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustodianGetProjectsUsers200ResponseDataWithDefaults() *CustodianGetProjectsUsers200ResponseData {
	this := CustodianGetProjectsUsers200ResponseData{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *CustodianGetProjectsUsers200ResponseData) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *CustodianGetProjectsUsers200ResponseData) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *CustodianGetProjectsUsers200ResponseData) SetTotal(v int32) {
	o.Total = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetData() []CustodianGetProjectsUsers200ResponseDataDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []CustodianGetProjectsUsers200ResponseDataDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetDataOk() ([]CustodianGetProjectsUsers200ResponseDataDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CustodianGetProjectsUsers200ResponseDataDataInner and assigns it to the Data field.
func (o *CustodianGetProjectsUsers200ResponseData) SetData(v []CustodianGetProjectsUsers200ResponseDataDataInner) {
	o.Data = v
}

// GetFirstPageUrl returns the FirstPageUrl field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetFirstPageUrl() string {
	if o == nil || IsNil(o.FirstPageUrl) {
		var ret string
		return ret
	}
	return *o.FirstPageUrl
}

// GetFirstPageUrlOk returns a tuple with the FirstPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetFirstPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FirstPageUrl) {
		return nil, false
	}
	return o.FirstPageUrl, true
}

// HasFirstPageUrl returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasFirstPageUrl() bool {
	if o != nil && !IsNil(o.FirstPageUrl) {
		return true
	}

	return false
}

// SetFirstPageUrl gets a reference to the given string and assigns it to the FirstPageUrl field.
func (o *CustodianGetProjectsUsers200ResponseData) SetFirstPageUrl(v string) {
	o.FirstPageUrl = &v
}

// GetLastPageUrl returns the LastPageUrl field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetLastPageUrl() string {
	if o == nil || IsNil(o.LastPageUrl) {
		var ret string
		return ret
	}
	return *o.LastPageUrl
}

// GetLastPageUrlOk returns a tuple with the LastPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetLastPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LastPageUrl) {
		return nil, false
	}
	return o.LastPageUrl, true
}

// HasLastPageUrl returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasLastPageUrl() bool {
	if o != nil && !IsNil(o.LastPageUrl) {
		return true
	}

	return false
}

// SetLastPageUrl gets a reference to the given string and assigns it to the LastPageUrl field.
func (o *CustodianGetProjectsUsers200ResponseData) SetLastPageUrl(v string) {
	o.LastPageUrl = &v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl) {
		var ret string
		return ret
	}
	return *o.NextPageUrl
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetNextPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageUrl) {
		return nil, false
	}
	return o.NextPageUrl, true
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasNextPageUrl() bool {
	if o != nil && !IsNil(o.NextPageUrl) {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given string and assigns it to the NextPageUrl field.
func (o *CustodianGetProjectsUsers200ResponseData) SetNextPageUrl(v string) {
	o.NextPageUrl = &v
}

// GetPrevPageUrl returns the PrevPageUrl field value if set, zero value otherwise.
func (o *CustodianGetProjectsUsers200ResponseData) GetPrevPageUrl() string {
	if o == nil || IsNil(o.PrevPageUrl) {
		var ret string
		return ret
	}
	return *o.PrevPageUrl
}

// GetPrevPageUrlOk returns a tuple with the PrevPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustodianGetProjectsUsers200ResponseData) GetPrevPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PrevPageUrl) {
		return nil, false
	}
	return o.PrevPageUrl, true
}

// HasPrevPageUrl returns a boolean if a field has been set.
func (o *CustodianGetProjectsUsers200ResponseData) HasPrevPageUrl() bool {
	if o != nil && !IsNil(o.PrevPageUrl) {
		return true
	}

	return false
}

// SetPrevPageUrl gets a reference to the given string and assigns it to the PrevPageUrl field.
func (o *CustodianGetProjectsUsers200ResponseData) SetPrevPageUrl(v string) {
	o.PrevPageUrl = &v
}

func (o CustodianGetProjectsUsers200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustodianGetProjectsUsers200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.FirstPageUrl) {
		toSerialize["first_page_url"] = o.FirstPageUrl
	}
	if !IsNil(o.LastPageUrl) {
		toSerialize["last_page_url"] = o.LastPageUrl
	}
	if !IsNil(o.NextPageUrl) {
		toSerialize["next_page_url"] = o.NextPageUrl
	}
	if !IsNil(o.PrevPageUrl) {
		toSerialize["prev_page_url"] = o.PrevPageUrl
	}
	return toSerialize, nil
}

type NullableCustodianGetProjectsUsers200ResponseData struct {
	value *CustodianGetProjectsUsers200ResponseData
	isSet bool
}

func (v NullableCustodianGetProjectsUsers200ResponseData) Get() *CustodianGetProjectsUsers200ResponseData {
	return v.value
}

func (v *NullableCustodianGetProjectsUsers200ResponseData) Set(val *CustodianGetProjectsUsers200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianGetProjectsUsers200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianGetProjectsUsers200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianGetProjectsUsers200ResponseData(val *CustodianGetProjectsUsers200ResponseData) *NullableCustodianGetProjectsUsers200ResponseData {
	return &NullableCustodianGetProjectsUsers200ResponseData{value: val, isSet: true}
}

func (v NullableCustodianGetProjectsUsers200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianGetProjectsUsers200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


