/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistrysdk

import (
	"encoding/json"
)

// checks if the Organisation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Organisation{}

// Organisation Organisation model
type Organisation struct {
	// Model primary key
	Id *int32 `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	OrganisationName *string `json:"organisation_name,omitempty"`
	Address1 *string `json:"address_1,omitempty"`
	Address2 *string `json:"address_2,omitempty"`
	Town *string `json:"town,omitempty"`
	County *string `json:"county,omitempty"`
	Country *string `json:"country,omitempty"`
	Postcode *string `json:"postcode,omitempty"`
	LeadApplicantOrganisationName *string `json:"lead_applicant_organisation_name,omitempty"`
	LeadApplicantEmail *string `json:"lead_applicant_email,omitempty"`
	OrganisationUniqueId *string `json:"organisation_unique_id,omitempty"`
	ApplicantNames *string `json:"applicant_names,omitempty"`
	FundersAndSponsors *string `json:"funders_and_sponsors,omitempty"`
	SubLicenseArrangements *string `json:"sub_license_arrangements,omitempty"`
	Verified *bool `json:"verified,omitempty"`
	DsptkOdsCode *string `json:"dsptk_ods_code,omitempty"`
	DsptkCertified *bool `json:"dsptk_certified,omitempty"`
	DsptkExpiryDate *string `json:"dsptk_expiry_date,omitempty"`
	Iso27001Certified *bool `json:"iso_27001_certified,omitempty"`
	Iso27001CertificationNum *string `json:"iso_27001_certification_num,omitempty"`
	IsoExpiryDate *string `json:"iso_expiry_date,omitempty"`
	CeCertified *bool `json:"ce_certified,omitempty"`
	CeCertificationNum *string `json:"ce_certification_num,omitempty"`
	CeExpiryDate *string `json:"ce_expiry_date,omitempty"`
	CePlusCertified *bool `json:"ce_plus_certified,omitempty"`
	CePlusCertificationNum *string `json:"ce_plus_certification_num,omitempty"`
	CePlusExpiryDate *string `json:"ce_plus_expiry_date,omitempty"`
	IdvtResult *int32 `json:"idvt_result,omitempty"`
	IdvtResultPerc *int32 `json:"idvt_result_perc,omitempty"`
	IdvtErrors *string `json:"idvt_errors,omitempty"`
	IdvtCompletedAt *string `json:"idvt_completed_at,omitempty"`
	CompaniesHouseNo *string `json:"companies_house_no,omitempty"`
	SectorId *int32 `json:"sector_id,omitempty"`
	// ROR.org identification for Research Organisations
	RorId *string `json:"ror_id,omitempty"`
	Website *string `json:"website,omitempty"`
	// Declaration of small/medium business
	SmbStatus *bool `json:"smb_status,omitempty"`
	// Organisation size. Integer denotes list index rather than absolute value
	OrganisationSize *int32 `json:"organisation_size,omitempty"`
	// Unclaimed
	Unclaimed *bool `json:"unclaimed,omitempty"`
	// Whether this Organisation has been approved to use the system or not
	SystemApproved *bool `json:"system_approved,omitempty"`
	OdsId *string `json:"ods_id,omitempty"`
	DsptkStatus *string `json:"dsptk_status,omitempty"`
	DsptkDateLastPublished *string `json:"dsptk_date_last_published,omitempty"`
	IcoRegistrationId *string `json:"ico_registration_id,omitempty"`
	IcoDateRegistered *string `json:"ico_date_registered,omitempty"`
	IcoExpiryDate *string `json:"ico_expiry_date,omitempty"`
}

// NewOrganisation instantiates a new Organisation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganisation() *Organisation {
	this := Organisation{}
	return &this
}

// NewOrganisationWithDefaults instantiates a new Organisation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganisationWithDefaults() *Organisation {
	this := Organisation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Organisation) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Organisation) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Organisation) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Organisation) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Organisation) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Organisation) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Organisation) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Organisation) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Organisation) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetOrganisationName returns the OrganisationName field value if set, zero value otherwise.
func (o *Organisation) GetOrganisationName() string {
	if o == nil || IsNil(o.OrganisationName) {
		var ret string
		return ret
	}
	return *o.OrganisationName
}

// GetOrganisationNameOk returns a tuple with the OrganisationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetOrganisationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrganisationName) {
		return nil, false
	}
	return o.OrganisationName, true
}

// HasOrganisationName returns a boolean if a field has been set.
func (o *Organisation) HasOrganisationName() bool {
	if o != nil && !IsNil(o.OrganisationName) {
		return true
	}

	return false
}

// SetOrganisationName gets a reference to the given string and assigns it to the OrganisationName field.
func (o *Organisation) SetOrganisationName(v string) {
	o.OrganisationName = &v
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise.
func (o *Organisation) GetAddress1() string {
	if o == nil || IsNil(o.Address1) {
		var ret string
		return ret
	}
	return *o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetAddress1Ok() (*string, bool) {
	if o == nil || IsNil(o.Address1) {
		return nil, false
	}
	return o.Address1, true
}

// HasAddress1 returns a boolean if a field has been set.
func (o *Organisation) HasAddress1() bool {
	if o != nil && !IsNil(o.Address1) {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given string and assigns it to the Address1 field.
func (o *Organisation) SetAddress1(v string) {
	o.Address1 = &v
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise.
func (o *Organisation) GetAddress2() string {
	if o == nil || IsNil(o.Address2) {
		var ret string
		return ret
	}
	return *o.Address2
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetAddress2Ok() (*string, bool) {
	if o == nil || IsNil(o.Address2) {
		return nil, false
	}
	return o.Address2, true
}

// HasAddress2 returns a boolean if a field has been set.
func (o *Organisation) HasAddress2() bool {
	if o != nil && !IsNil(o.Address2) {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given string and assigns it to the Address2 field.
func (o *Organisation) SetAddress2(v string) {
	o.Address2 = &v
}

// GetTown returns the Town field value if set, zero value otherwise.
func (o *Organisation) GetTown() string {
	if o == nil || IsNil(o.Town) {
		var ret string
		return ret
	}
	return *o.Town
}

// GetTownOk returns a tuple with the Town field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetTownOk() (*string, bool) {
	if o == nil || IsNil(o.Town) {
		return nil, false
	}
	return o.Town, true
}

// HasTown returns a boolean if a field has been set.
func (o *Organisation) HasTown() bool {
	if o != nil && !IsNil(o.Town) {
		return true
	}

	return false
}

// SetTown gets a reference to the given string and assigns it to the Town field.
func (o *Organisation) SetTown(v string) {
	o.Town = &v
}

// GetCounty returns the County field value if set, zero value otherwise.
func (o *Organisation) GetCounty() string {
	if o == nil || IsNil(o.County) {
		var ret string
		return ret
	}
	return *o.County
}

// GetCountyOk returns a tuple with the County field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCountyOk() (*string, bool) {
	if o == nil || IsNil(o.County) {
		return nil, false
	}
	return o.County, true
}

// HasCounty returns a boolean if a field has been set.
func (o *Organisation) HasCounty() bool {
	if o != nil && !IsNil(o.County) {
		return true
	}

	return false
}

// SetCounty gets a reference to the given string and assigns it to the County field.
func (o *Organisation) SetCounty(v string) {
	o.County = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *Organisation) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *Organisation) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *Organisation) SetCountry(v string) {
	o.Country = &v
}

// GetPostcode returns the Postcode field value if set, zero value otherwise.
func (o *Organisation) GetPostcode() string {
	if o == nil || IsNil(o.Postcode) {
		var ret string
		return ret
	}
	return *o.Postcode
}

// GetPostcodeOk returns a tuple with the Postcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetPostcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Postcode) {
		return nil, false
	}
	return o.Postcode, true
}

// HasPostcode returns a boolean if a field has been set.
func (o *Organisation) HasPostcode() bool {
	if o != nil && !IsNil(o.Postcode) {
		return true
	}

	return false
}

// SetPostcode gets a reference to the given string and assigns it to the Postcode field.
func (o *Organisation) SetPostcode(v string) {
	o.Postcode = &v
}

// GetLeadApplicantOrganisationName returns the LeadApplicantOrganisationName field value if set, zero value otherwise.
func (o *Organisation) GetLeadApplicantOrganisationName() string {
	if o == nil || IsNil(o.LeadApplicantOrganisationName) {
		var ret string
		return ret
	}
	return *o.LeadApplicantOrganisationName
}

// GetLeadApplicantOrganisationNameOk returns a tuple with the LeadApplicantOrganisationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetLeadApplicantOrganisationNameOk() (*string, bool) {
	if o == nil || IsNil(o.LeadApplicantOrganisationName) {
		return nil, false
	}
	return o.LeadApplicantOrganisationName, true
}

// HasLeadApplicantOrganisationName returns a boolean if a field has been set.
func (o *Organisation) HasLeadApplicantOrganisationName() bool {
	if o != nil && !IsNil(o.LeadApplicantOrganisationName) {
		return true
	}

	return false
}

// SetLeadApplicantOrganisationName gets a reference to the given string and assigns it to the LeadApplicantOrganisationName field.
func (o *Organisation) SetLeadApplicantOrganisationName(v string) {
	o.LeadApplicantOrganisationName = &v
}

// GetLeadApplicantEmail returns the LeadApplicantEmail field value if set, zero value otherwise.
func (o *Organisation) GetLeadApplicantEmail() string {
	if o == nil || IsNil(o.LeadApplicantEmail) {
		var ret string
		return ret
	}
	return *o.LeadApplicantEmail
}

// GetLeadApplicantEmailOk returns a tuple with the LeadApplicantEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetLeadApplicantEmailOk() (*string, bool) {
	if o == nil || IsNil(o.LeadApplicantEmail) {
		return nil, false
	}
	return o.LeadApplicantEmail, true
}

// HasLeadApplicantEmail returns a boolean if a field has been set.
func (o *Organisation) HasLeadApplicantEmail() bool {
	if o != nil && !IsNil(o.LeadApplicantEmail) {
		return true
	}

	return false
}

// SetLeadApplicantEmail gets a reference to the given string and assigns it to the LeadApplicantEmail field.
func (o *Organisation) SetLeadApplicantEmail(v string) {
	o.LeadApplicantEmail = &v
}

// GetOrganisationUniqueId returns the OrganisationUniqueId field value if set, zero value otherwise.
func (o *Organisation) GetOrganisationUniqueId() string {
	if o == nil || IsNil(o.OrganisationUniqueId) {
		var ret string
		return ret
	}
	return *o.OrganisationUniqueId
}

// GetOrganisationUniqueIdOk returns a tuple with the OrganisationUniqueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetOrganisationUniqueIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganisationUniqueId) {
		return nil, false
	}
	return o.OrganisationUniqueId, true
}

// HasOrganisationUniqueId returns a boolean if a field has been set.
func (o *Organisation) HasOrganisationUniqueId() bool {
	if o != nil && !IsNil(o.OrganisationUniqueId) {
		return true
	}

	return false
}

// SetOrganisationUniqueId gets a reference to the given string and assigns it to the OrganisationUniqueId field.
func (o *Organisation) SetOrganisationUniqueId(v string) {
	o.OrganisationUniqueId = &v
}

// GetApplicantNames returns the ApplicantNames field value if set, zero value otherwise.
func (o *Organisation) GetApplicantNames() string {
	if o == nil || IsNil(o.ApplicantNames) {
		var ret string
		return ret
	}
	return *o.ApplicantNames
}

// GetApplicantNamesOk returns a tuple with the ApplicantNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetApplicantNamesOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicantNames) {
		return nil, false
	}
	return o.ApplicantNames, true
}

// HasApplicantNames returns a boolean if a field has been set.
func (o *Organisation) HasApplicantNames() bool {
	if o != nil && !IsNil(o.ApplicantNames) {
		return true
	}

	return false
}

// SetApplicantNames gets a reference to the given string and assigns it to the ApplicantNames field.
func (o *Organisation) SetApplicantNames(v string) {
	o.ApplicantNames = &v
}

// GetFundersAndSponsors returns the FundersAndSponsors field value if set, zero value otherwise.
func (o *Organisation) GetFundersAndSponsors() string {
	if o == nil || IsNil(o.FundersAndSponsors) {
		var ret string
		return ret
	}
	return *o.FundersAndSponsors
}

// GetFundersAndSponsorsOk returns a tuple with the FundersAndSponsors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetFundersAndSponsorsOk() (*string, bool) {
	if o == nil || IsNil(o.FundersAndSponsors) {
		return nil, false
	}
	return o.FundersAndSponsors, true
}

// HasFundersAndSponsors returns a boolean if a field has been set.
func (o *Organisation) HasFundersAndSponsors() bool {
	if o != nil && !IsNil(o.FundersAndSponsors) {
		return true
	}

	return false
}

// SetFundersAndSponsors gets a reference to the given string and assigns it to the FundersAndSponsors field.
func (o *Organisation) SetFundersAndSponsors(v string) {
	o.FundersAndSponsors = &v
}

// GetSubLicenseArrangements returns the SubLicenseArrangements field value if set, zero value otherwise.
func (o *Organisation) GetSubLicenseArrangements() string {
	if o == nil || IsNil(o.SubLicenseArrangements) {
		var ret string
		return ret
	}
	return *o.SubLicenseArrangements
}

// GetSubLicenseArrangementsOk returns a tuple with the SubLicenseArrangements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetSubLicenseArrangementsOk() (*string, bool) {
	if o == nil || IsNil(o.SubLicenseArrangements) {
		return nil, false
	}
	return o.SubLicenseArrangements, true
}

// HasSubLicenseArrangements returns a boolean if a field has been set.
func (o *Organisation) HasSubLicenseArrangements() bool {
	if o != nil && !IsNil(o.SubLicenseArrangements) {
		return true
	}

	return false
}

// SetSubLicenseArrangements gets a reference to the given string and assigns it to the SubLicenseArrangements field.
func (o *Organisation) SetSubLicenseArrangements(v string) {
	o.SubLicenseArrangements = &v
}

// GetVerified returns the Verified field value if set, zero value otherwise.
func (o *Organisation) GetVerified() bool {
	if o == nil || IsNil(o.Verified) {
		var ret bool
		return ret
	}
	return *o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Verified) {
		return nil, false
	}
	return o.Verified, true
}

// HasVerified returns a boolean if a field has been set.
func (o *Organisation) HasVerified() bool {
	if o != nil && !IsNil(o.Verified) {
		return true
	}

	return false
}

// SetVerified gets a reference to the given bool and assigns it to the Verified field.
func (o *Organisation) SetVerified(v bool) {
	o.Verified = &v
}

// GetDsptkOdsCode returns the DsptkOdsCode field value if set, zero value otherwise.
func (o *Organisation) GetDsptkOdsCode() string {
	if o == nil || IsNil(o.DsptkOdsCode) {
		var ret string
		return ret
	}
	return *o.DsptkOdsCode
}

// GetDsptkOdsCodeOk returns a tuple with the DsptkOdsCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetDsptkOdsCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DsptkOdsCode) {
		return nil, false
	}
	return o.DsptkOdsCode, true
}

// HasDsptkOdsCode returns a boolean if a field has been set.
func (o *Organisation) HasDsptkOdsCode() bool {
	if o != nil && !IsNil(o.DsptkOdsCode) {
		return true
	}

	return false
}

// SetDsptkOdsCode gets a reference to the given string and assigns it to the DsptkOdsCode field.
func (o *Organisation) SetDsptkOdsCode(v string) {
	o.DsptkOdsCode = &v
}

// GetDsptkCertified returns the DsptkCertified field value if set, zero value otherwise.
func (o *Organisation) GetDsptkCertified() bool {
	if o == nil || IsNil(o.DsptkCertified) {
		var ret bool
		return ret
	}
	return *o.DsptkCertified
}

// GetDsptkCertifiedOk returns a tuple with the DsptkCertified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetDsptkCertifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.DsptkCertified) {
		return nil, false
	}
	return o.DsptkCertified, true
}

// HasDsptkCertified returns a boolean if a field has been set.
func (o *Organisation) HasDsptkCertified() bool {
	if o != nil && !IsNil(o.DsptkCertified) {
		return true
	}

	return false
}

// SetDsptkCertified gets a reference to the given bool and assigns it to the DsptkCertified field.
func (o *Organisation) SetDsptkCertified(v bool) {
	o.DsptkCertified = &v
}

// GetDsptkExpiryDate returns the DsptkExpiryDate field value if set, zero value otherwise.
func (o *Organisation) GetDsptkExpiryDate() string {
	if o == nil || IsNil(o.DsptkExpiryDate) {
		var ret string
		return ret
	}
	return *o.DsptkExpiryDate
}

// GetDsptkExpiryDateOk returns a tuple with the DsptkExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetDsptkExpiryDateOk() (*string, bool) {
	if o == nil || IsNil(o.DsptkExpiryDate) {
		return nil, false
	}
	return o.DsptkExpiryDate, true
}

// HasDsptkExpiryDate returns a boolean if a field has been set.
func (o *Organisation) HasDsptkExpiryDate() bool {
	if o != nil && !IsNil(o.DsptkExpiryDate) {
		return true
	}

	return false
}

// SetDsptkExpiryDate gets a reference to the given string and assigns it to the DsptkExpiryDate field.
func (o *Organisation) SetDsptkExpiryDate(v string) {
	o.DsptkExpiryDate = &v
}

// GetIso27001Certified returns the Iso27001Certified field value if set, zero value otherwise.
func (o *Organisation) GetIso27001Certified() bool {
	if o == nil || IsNil(o.Iso27001Certified) {
		var ret bool
		return ret
	}
	return *o.Iso27001Certified
}

// GetIso27001CertifiedOk returns a tuple with the Iso27001Certified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIso27001CertifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Iso27001Certified) {
		return nil, false
	}
	return o.Iso27001Certified, true
}

// HasIso27001Certified returns a boolean if a field has been set.
func (o *Organisation) HasIso27001Certified() bool {
	if o != nil && !IsNil(o.Iso27001Certified) {
		return true
	}

	return false
}

// SetIso27001Certified gets a reference to the given bool and assigns it to the Iso27001Certified field.
func (o *Organisation) SetIso27001Certified(v bool) {
	o.Iso27001Certified = &v
}

// GetIso27001CertificationNum returns the Iso27001CertificationNum field value if set, zero value otherwise.
func (o *Organisation) GetIso27001CertificationNum() string {
	if o == nil || IsNil(o.Iso27001CertificationNum) {
		var ret string
		return ret
	}
	return *o.Iso27001CertificationNum
}

// GetIso27001CertificationNumOk returns a tuple with the Iso27001CertificationNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIso27001CertificationNumOk() (*string, bool) {
	if o == nil || IsNil(o.Iso27001CertificationNum) {
		return nil, false
	}
	return o.Iso27001CertificationNum, true
}

// HasIso27001CertificationNum returns a boolean if a field has been set.
func (o *Organisation) HasIso27001CertificationNum() bool {
	if o != nil && !IsNil(o.Iso27001CertificationNum) {
		return true
	}

	return false
}

// SetIso27001CertificationNum gets a reference to the given string and assigns it to the Iso27001CertificationNum field.
func (o *Organisation) SetIso27001CertificationNum(v string) {
	o.Iso27001CertificationNum = &v
}

// GetIsoExpiryDate returns the IsoExpiryDate field value if set, zero value otherwise.
func (o *Organisation) GetIsoExpiryDate() string {
	if o == nil || IsNil(o.IsoExpiryDate) {
		var ret string
		return ret
	}
	return *o.IsoExpiryDate
}

// GetIsoExpiryDateOk returns a tuple with the IsoExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIsoExpiryDateOk() (*string, bool) {
	if o == nil || IsNil(o.IsoExpiryDate) {
		return nil, false
	}
	return o.IsoExpiryDate, true
}

// HasIsoExpiryDate returns a boolean if a field has been set.
func (o *Organisation) HasIsoExpiryDate() bool {
	if o != nil && !IsNil(o.IsoExpiryDate) {
		return true
	}

	return false
}

// SetIsoExpiryDate gets a reference to the given string and assigns it to the IsoExpiryDate field.
func (o *Organisation) SetIsoExpiryDate(v string) {
	o.IsoExpiryDate = &v
}

// GetCeCertified returns the CeCertified field value if set, zero value otherwise.
func (o *Organisation) GetCeCertified() bool {
	if o == nil || IsNil(o.CeCertified) {
		var ret bool
		return ret
	}
	return *o.CeCertified
}

// GetCeCertifiedOk returns a tuple with the CeCertified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCeCertifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.CeCertified) {
		return nil, false
	}
	return o.CeCertified, true
}

// HasCeCertified returns a boolean if a field has been set.
func (o *Organisation) HasCeCertified() bool {
	if o != nil && !IsNil(o.CeCertified) {
		return true
	}

	return false
}

// SetCeCertified gets a reference to the given bool and assigns it to the CeCertified field.
func (o *Organisation) SetCeCertified(v bool) {
	o.CeCertified = &v
}

// GetCeCertificationNum returns the CeCertificationNum field value if set, zero value otherwise.
func (o *Organisation) GetCeCertificationNum() string {
	if o == nil || IsNil(o.CeCertificationNum) {
		var ret string
		return ret
	}
	return *o.CeCertificationNum
}

// GetCeCertificationNumOk returns a tuple with the CeCertificationNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCeCertificationNumOk() (*string, bool) {
	if o == nil || IsNil(o.CeCertificationNum) {
		return nil, false
	}
	return o.CeCertificationNum, true
}

// HasCeCertificationNum returns a boolean if a field has been set.
func (o *Organisation) HasCeCertificationNum() bool {
	if o != nil && !IsNil(o.CeCertificationNum) {
		return true
	}

	return false
}

// SetCeCertificationNum gets a reference to the given string and assigns it to the CeCertificationNum field.
func (o *Organisation) SetCeCertificationNum(v string) {
	o.CeCertificationNum = &v
}

// GetCeExpiryDate returns the CeExpiryDate field value if set, zero value otherwise.
func (o *Organisation) GetCeExpiryDate() string {
	if o == nil || IsNil(o.CeExpiryDate) {
		var ret string
		return ret
	}
	return *o.CeExpiryDate
}

// GetCeExpiryDateOk returns a tuple with the CeExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCeExpiryDateOk() (*string, bool) {
	if o == nil || IsNil(o.CeExpiryDate) {
		return nil, false
	}
	return o.CeExpiryDate, true
}

// HasCeExpiryDate returns a boolean if a field has been set.
func (o *Organisation) HasCeExpiryDate() bool {
	if o != nil && !IsNil(o.CeExpiryDate) {
		return true
	}

	return false
}

// SetCeExpiryDate gets a reference to the given string and assigns it to the CeExpiryDate field.
func (o *Organisation) SetCeExpiryDate(v string) {
	o.CeExpiryDate = &v
}

// GetCePlusCertified returns the CePlusCertified field value if set, zero value otherwise.
func (o *Organisation) GetCePlusCertified() bool {
	if o == nil || IsNil(o.CePlusCertified) {
		var ret bool
		return ret
	}
	return *o.CePlusCertified
}

// GetCePlusCertifiedOk returns a tuple with the CePlusCertified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCePlusCertifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.CePlusCertified) {
		return nil, false
	}
	return o.CePlusCertified, true
}

// HasCePlusCertified returns a boolean if a field has been set.
func (o *Organisation) HasCePlusCertified() bool {
	if o != nil && !IsNil(o.CePlusCertified) {
		return true
	}

	return false
}

// SetCePlusCertified gets a reference to the given bool and assigns it to the CePlusCertified field.
func (o *Organisation) SetCePlusCertified(v bool) {
	o.CePlusCertified = &v
}

// GetCePlusCertificationNum returns the CePlusCertificationNum field value if set, zero value otherwise.
func (o *Organisation) GetCePlusCertificationNum() string {
	if o == nil || IsNil(o.CePlusCertificationNum) {
		var ret string
		return ret
	}
	return *o.CePlusCertificationNum
}

// GetCePlusCertificationNumOk returns a tuple with the CePlusCertificationNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCePlusCertificationNumOk() (*string, bool) {
	if o == nil || IsNil(o.CePlusCertificationNum) {
		return nil, false
	}
	return o.CePlusCertificationNum, true
}

// HasCePlusCertificationNum returns a boolean if a field has been set.
func (o *Organisation) HasCePlusCertificationNum() bool {
	if o != nil && !IsNil(o.CePlusCertificationNum) {
		return true
	}

	return false
}

// SetCePlusCertificationNum gets a reference to the given string and assigns it to the CePlusCertificationNum field.
func (o *Organisation) SetCePlusCertificationNum(v string) {
	o.CePlusCertificationNum = &v
}

// GetCePlusExpiryDate returns the CePlusExpiryDate field value if set, zero value otherwise.
func (o *Organisation) GetCePlusExpiryDate() string {
	if o == nil || IsNil(o.CePlusExpiryDate) {
		var ret string
		return ret
	}
	return *o.CePlusExpiryDate
}

// GetCePlusExpiryDateOk returns a tuple with the CePlusExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCePlusExpiryDateOk() (*string, bool) {
	if o == nil || IsNil(o.CePlusExpiryDate) {
		return nil, false
	}
	return o.CePlusExpiryDate, true
}

// HasCePlusExpiryDate returns a boolean if a field has been set.
func (o *Organisation) HasCePlusExpiryDate() bool {
	if o != nil && !IsNil(o.CePlusExpiryDate) {
		return true
	}

	return false
}

// SetCePlusExpiryDate gets a reference to the given string and assigns it to the CePlusExpiryDate field.
func (o *Organisation) SetCePlusExpiryDate(v string) {
	o.CePlusExpiryDate = &v
}

// GetIdvtResult returns the IdvtResult field value if set, zero value otherwise.
func (o *Organisation) GetIdvtResult() int32 {
	if o == nil || IsNil(o.IdvtResult) {
		var ret int32
		return ret
	}
	return *o.IdvtResult
}

// GetIdvtResultOk returns a tuple with the IdvtResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIdvtResultOk() (*int32, bool) {
	if o == nil || IsNil(o.IdvtResult) {
		return nil, false
	}
	return o.IdvtResult, true
}

// HasIdvtResult returns a boolean if a field has been set.
func (o *Organisation) HasIdvtResult() bool {
	if o != nil && !IsNil(o.IdvtResult) {
		return true
	}

	return false
}

// SetIdvtResult gets a reference to the given int32 and assigns it to the IdvtResult field.
func (o *Organisation) SetIdvtResult(v int32) {
	o.IdvtResult = &v
}

// GetIdvtResultPerc returns the IdvtResultPerc field value if set, zero value otherwise.
func (o *Organisation) GetIdvtResultPerc() int32 {
	if o == nil || IsNil(o.IdvtResultPerc) {
		var ret int32
		return ret
	}
	return *o.IdvtResultPerc
}

// GetIdvtResultPercOk returns a tuple with the IdvtResultPerc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIdvtResultPercOk() (*int32, bool) {
	if o == nil || IsNil(o.IdvtResultPerc) {
		return nil, false
	}
	return o.IdvtResultPerc, true
}

// HasIdvtResultPerc returns a boolean if a field has been set.
func (o *Organisation) HasIdvtResultPerc() bool {
	if o != nil && !IsNil(o.IdvtResultPerc) {
		return true
	}

	return false
}

// SetIdvtResultPerc gets a reference to the given int32 and assigns it to the IdvtResultPerc field.
func (o *Organisation) SetIdvtResultPerc(v int32) {
	o.IdvtResultPerc = &v
}

// GetIdvtErrors returns the IdvtErrors field value if set, zero value otherwise.
func (o *Organisation) GetIdvtErrors() string {
	if o == nil || IsNil(o.IdvtErrors) {
		var ret string
		return ret
	}
	return *o.IdvtErrors
}

// GetIdvtErrorsOk returns a tuple with the IdvtErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIdvtErrorsOk() (*string, bool) {
	if o == nil || IsNil(o.IdvtErrors) {
		return nil, false
	}
	return o.IdvtErrors, true
}

// HasIdvtErrors returns a boolean if a field has been set.
func (o *Organisation) HasIdvtErrors() bool {
	if o != nil && !IsNil(o.IdvtErrors) {
		return true
	}

	return false
}

// SetIdvtErrors gets a reference to the given string and assigns it to the IdvtErrors field.
func (o *Organisation) SetIdvtErrors(v string) {
	o.IdvtErrors = &v
}

// GetIdvtCompletedAt returns the IdvtCompletedAt field value if set, zero value otherwise.
func (o *Organisation) GetIdvtCompletedAt() string {
	if o == nil || IsNil(o.IdvtCompletedAt) {
		var ret string
		return ret
	}
	return *o.IdvtCompletedAt
}

// GetIdvtCompletedAtOk returns a tuple with the IdvtCompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIdvtCompletedAtOk() (*string, bool) {
	if o == nil || IsNil(o.IdvtCompletedAt) {
		return nil, false
	}
	return o.IdvtCompletedAt, true
}

// HasIdvtCompletedAt returns a boolean if a field has been set.
func (o *Organisation) HasIdvtCompletedAt() bool {
	if o != nil && !IsNil(o.IdvtCompletedAt) {
		return true
	}

	return false
}

// SetIdvtCompletedAt gets a reference to the given string and assigns it to the IdvtCompletedAt field.
func (o *Organisation) SetIdvtCompletedAt(v string) {
	o.IdvtCompletedAt = &v
}

// GetCompaniesHouseNo returns the CompaniesHouseNo field value if set, zero value otherwise.
func (o *Organisation) GetCompaniesHouseNo() string {
	if o == nil || IsNil(o.CompaniesHouseNo) {
		var ret string
		return ret
	}
	return *o.CompaniesHouseNo
}

// GetCompaniesHouseNoOk returns a tuple with the CompaniesHouseNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetCompaniesHouseNoOk() (*string, bool) {
	if o == nil || IsNil(o.CompaniesHouseNo) {
		return nil, false
	}
	return o.CompaniesHouseNo, true
}

// HasCompaniesHouseNo returns a boolean if a field has been set.
func (o *Organisation) HasCompaniesHouseNo() bool {
	if o != nil && !IsNil(o.CompaniesHouseNo) {
		return true
	}

	return false
}

// SetCompaniesHouseNo gets a reference to the given string and assigns it to the CompaniesHouseNo field.
func (o *Organisation) SetCompaniesHouseNo(v string) {
	o.CompaniesHouseNo = &v
}

// GetSectorId returns the SectorId field value if set, zero value otherwise.
func (o *Organisation) GetSectorId() int32 {
	if o == nil || IsNil(o.SectorId) {
		var ret int32
		return ret
	}
	return *o.SectorId
}

// GetSectorIdOk returns a tuple with the SectorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetSectorIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SectorId) {
		return nil, false
	}
	return o.SectorId, true
}

// HasSectorId returns a boolean if a field has been set.
func (o *Organisation) HasSectorId() bool {
	if o != nil && !IsNil(o.SectorId) {
		return true
	}

	return false
}

// SetSectorId gets a reference to the given int32 and assigns it to the SectorId field.
func (o *Organisation) SetSectorId(v int32) {
	o.SectorId = &v
}

// GetRorId returns the RorId field value if set, zero value otherwise.
func (o *Organisation) GetRorId() string {
	if o == nil || IsNil(o.RorId) {
		var ret string
		return ret
	}
	return *o.RorId
}

// GetRorIdOk returns a tuple with the RorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetRorIdOk() (*string, bool) {
	if o == nil || IsNil(o.RorId) {
		return nil, false
	}
	return o.RorId, true
}

// HasRorId returns a boolean if a field has been set.
func (o *Organisation) HasRorId() bool {
	if o != nil && !IsNil(o.RorId) {
		return true
	}

	return false
}

// SetRorId gets a reference to the given string and assigns it to the RorId field.
func (o *Organisation) SetRorId(v string) {
	o.RorId = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *Organisation) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *Organisation) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *Organisation) SetWebsite(v string) {
	o.Website = &v
}

// GetSmbStatus returns the SmbStatus field value if set, zero value otherwise.
func (o *Organisation) GetSmbStatus() bool {
	if o == nil || IsNil(o.SmbStatus) {
		var ret bool
		return ret
	}
	return *o.SmbStatus
}

// GetSmbStatusOk returns a tuple with the SmbStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetSmbStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.SmbStatus) {
		return nil, false
	}
	return o.SmbStatus, true
}

// HasSmbStatus returns a boolean if a field has been set.
func (o *Organisation) HasSmbStatus() bool {
	if o != nil && !IsNil(o.SmbStatus) {
		return true
	}

	return false
}

// SetSmbStatus gets a reference to the given bool and assigns it to the SmbStatus field.
func (o *Organisation) SetSmbStatus(v bool) {
	o.SmbStatus = &v
}

// GetOrganisationSize returns the OrganisationSize field value if set, zero value otherwise.
func (o *Organisation) GetOrganisationSize() int32 {
	if o == nil || IsNil(o.OrganisationSize) {
		var ret int32
		return ret
	}
	return *o.OrganisationSize
}

// GetOrganisationSizeOk returns a tuple with the OrganisationSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetOrganisationSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganisationSize) {
		return nil, false
	}
	return o.OrganisationSize, true
}

// HasOrganisationSize returns a boolean if a field has been set.
func (o *Organisation) HasOrganisationSize() bool {
	if o != nil && !IsNil(o.OrganisationSize) {
		return true
	}

	return false
}

// SetOrganisationSize gets a reference to the given int32 and assigns it to the OrganisationSize field.
func (o *Organisation) SetOrganisationSize(v int32) {
	o.OrganisationSize = &v
}

// GetUnclaimed returns the Unclaimed field value if set, zero value otherwise.
func (o *Organisation) GetUnclaimed() bool {
	if o == nil || IsNil(o.Unclaimed) {
		var ret bool
		return ret
	}
	return *o.Unclaimed
}

// GetUnclaimedOk returns a tuple with the Unclaimed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetUnclaimedOk() (*bool, bool) {
	if o == nil || IsNil(o.Unclaimed) {
		return nil, false
	}
	return o.Unclaimed, true
}

// HasUnclaimed returns a boolean if a field has been set.
func (o *Organisation) HasUnclaimed() bool {
	if o != nil && !IsNil(o.Unclaimed) {
		return true
	}

	return false
}

// SetUnclaimed gets a reference to the given bool and assigns it to the Unclaimed field.
func (o *Organisation) SetUnclaimed(v bool) {
	o.Unclaimed = &v
}

// GetSystemApproved returns the SystemApproved field value if set, zero value otherwise.
func (o *Organisation) GetSystemApproved() bool {
	if o == nil || IsNil(o.SystemApproved) {
		var ret bool
		return ret
	}
	return *o.SystemApproved
}

// GetSystemApprovedOk returns a tuple with the SystemApproved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetSystemApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.SystemApproved) {
		return nil, false
	}
	return o.SystemApproved, true
}

// HasSystemApproved returns a boolean if a field has been set.
func (o *Organisation) HasSystemApproved() bool {
	if o != nil && !IsNil(o.SystemApproved) {
		return true
	}

	return false
}

// SetSystemApproved gets a reference to the given bool and assigns it to the SystemApproved field.
func (o *Organisation) SetSystemApproved(v bool) {
	o.SystemApproved = &v
}

// GetOdsId returns the OdsId field value if set, zero value otherwise.
func (o *Organisation) GetOdsId() string {
	if o == nil || IsNil(o.OdsId) {
		var ret string
		return ret
	}
	return *o.OdsId
}

// GetOdsIdOk returns a tuple with the OdsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetOdsIdOk() (*string, bool) {
	if o == nil || IsNil(o.OdsId) {
		return nil, false
	}
	return o.OdsId, true
}

// HasOdsId returns a boolean if a field has been set.
func (o *Organisation) HasOdsId() bool {
	if o != nil && !IsNil(o.OdsId) {
		return true
	}

	return false
}

// SetOdsId gets a reference to the given string and assigns it to the OdsId field.
func (o *Organisation) SetOdsId(v string) {
	o.OdsId = &v
}

// GetDsptkStatus returns the DsptkStatus field value if set, zero value otherwise.
func (o *Organisation) GetDsptkStatus() string {
	if o == nil || IsNil(o.DsptkStatus) {
		var ret string
		return ret
	}
	return *o.DsptkStatus
}

// GetDsptkStatusOk returns a tuple with the DsptkStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetDsptkStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DsptkStatus) {
		return nil, false
	}
	return o.DsptkStatus, true
}

// HasDsptkStatus returns a boolean if a field has been set.
func (o *Organisation) HasDsptkStatus() bool {
	if o != nil && !IsNil(o.DsptkStatus) {
		return true
	}

	return false
}

// SetDsptkStatus gets a reference to the given string and assigns it to the DsptkStatus field.
func (o *Organisation) SetDsptkStatus(v string) {
	o.DsptkStatus = &v
}

// GetDsptkDateLastPublished returns the DsptkDateLastPublished field value if set, zero value otherwise.
func (o *Organisation) GetDsptkDateLastPublished() string {
	if o == nil || IsNil(o.DsptkDateLastPublished) {
		var ret string
		return ret
	}
	return *o.DsptkDateLastPublished
}

// GetDsptkDateLastPublishedOk returns a tuple with the DsptkDateLastPublished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetDsptkDateLastPublishedOk() (*string, bool) {
	if o == nil || IsNil(o.DsptkDateLastPublished) {
		return nil, false
	}
	return o.DsptkDateLastPublished, true
}

// HasDsptkDateLastPublished returns a boolean if a field has been set.
func (o *Organisation) HasDsptkDateLastPublished() bool {
	if o != nil && !IsNil(o.DsptkDateLastPublished) {
		return true
	}

	return false
}

// SetDsptkDateLastPublished gets a reference to the given string and assigns it to the DsptkDateLastPublished field.
func (o *Organisation) SetDsptkDateLastPublished(v string) {
	o.DsptkDateLastPublished = &v
}

// GetIcoRegistrationId returns the IcoRegistrationId field value if set, zero value otherwise.
func (o *Organisation) GetIcoRegistrationId() string {
	if o == nil || IsNil(o.IcoRegistrationId) {
		var ret string
		return ret
	}
	return *o.IcoRegistrationId
}

// GetIcoRegistrationIdOk returns a tuple with the IcoRegistrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIcoRegistrationIdOk() (*string, bool) {
	if o == nil || IsNil(o.IcoRegistrationId) {
		return nil, false
	}
	return o.IcoRegistrationId, true
}

// HasIcoRegistrationId returns a boolean if a field has been set.
func (o *Organisation) HasIcoRegistrationId() bool {
	if o != nil && !IsNil(o.IcoRegistrationId) {
		return true
	}

	return false
}

// SetIcoRegistrationId gets a reference to the given string and assigns it to the IcoRegistrationId field.
func (o *Organisation) SetIcoRegistrationId(v string) {
	o.IcoRegistrationId = &v
}

// GetIcoDateRegistered returns the IcoDateRegistered field value if set, zero value otherwise.
func (o *Organisation) GetIcoDateRegistered() string {
	if o == nil || IsNil(o.IcoDateRegistered) {
		var ret string
		return ret
	}
	return *o.IcoDateRegistered
}

// GetIcoDateRegisteredOk returns a tuple with the IcoDateRegistered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIcoDateRegisteredOk() (*string, bool) {
	if o == nil || IsNil(o.IcoDateRegistered) {
		return nil, false
	}
	return o.IcoDateRegistered, true
}

// HasIcoDateRegistered returns a boolean if a field has been set.
func (o *Organisation) HasIcoDateRegistered() bool {
	if o != nil && !IsNil(o.IcoDateRegistered) {
		return true
	}

	return false
}

// SetIcoDateRegistered gets a reference to the given string and assigns it to the IcoDateRegistered field.
func (o *Organisation) SetIcoDateRegistered(v string) {
	o.IcoDateRegistered = &v
}

// GetIcoExpiryDate returns the IcoExpiryDate field value if set, zero value otherwise.
func (o *Organisation) GetIcoExpiryDate() string {
	if o == nil || IsNil(o.IcoExpiryDate) {
		var ret string
		return ret
	}
	return *o.IcoExpiryDate
}

// GetIcoExpiryDateOk returns a tuple with the IcoExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Organisation) GetIcoExpiryDateOk() (*string, bool) {
	if o == nil || IsNil(o.IcoExpiryDate) {
		return nil, false
	}
	return o.IcoExpiryDate, true
}

// HasIcoExpiryDate returns a boolean if a field has been set.
func (o *Organisation) HasIcoExpiryDate() bool {
	if o != nil && !IsNil(o.IcoExpiryDate) {
		return true
	}

	return false
}

// SetIcoExpiryDate gets a reference to the given string and assigns it to the IcoExpiryDate field.
func (o *Organisation) SetIcoExpiryDate(v string) {
	o.IcoExpiryDate = &v
}

func (o Organisation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Organisation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.OrganisationName) {
		toSerialize["organisation_name"] = o.OrganisationName
	}
	if !IsNil(o.Address1) {
		toSerialize["address_1"] = o.Address1
	}
	if !IsNil(o.Address2) {
		toSerialize["address_2"] = o.Address2
	}
	if !IsNil(o.Town) {
		toSerialize["town"] = o.Town
	}
	if !IsNil(o.County) {
		toSerialize["county"] = o.County
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Postcode) {
		toSerialize["postcode"] = o.Postcode
	}
	if !IsNil(o.LeadApplicantOrganisationName) {
		toSerialize["lead_applicant_organisation_name"] = o.LeadApplicantOrganisationName
	}
	if !IsNil(o.LeadApplicantEmail) {
		toSerialize["lead_applicant_email"] = o.LeadApplicantEmail
	}
	if !IsNil(o.OrganisationUniqueId) {
		toSerialize["organisation_unique_id"] = o.OrganisationUniqueId
	}
	if !IsNil(o.ApplicantNames) {
		toSerialize["applicant_names"] = o.ApplicantNames
	}
	if !IsNil(o.FundersAndSponsors) {
		toSerialize["funders_and_sponsors"] = o.FundersAndSponsors
	}
	if !IsNil(o.SubLicenseArrangements) {
		toSerialize["sub_license_arrangements"] = o.SubLicenseArrangements
	}
	if !IsNil(o.Verified) {
		toSerialize["verified"] = o.Verified
	}
	if !IsNil(o.DsptkOdsCode) {
		toSerialize["dsptk_ods_code"] = o.DsptkOdsCode
	}
	if !IsNil(o.DsptkCertified) {
		toSerialize["dsptk_certified"] = o.DsptkCertified
	}
	if !IsNil(o.DsptkExpiryDate) {
		toSerialize["dsptk_expiry_date"] = o.DsptkExpiryDate
	}
	if !IsNil(o.Iso27001Certified) {
		toSerialize["iso_27001_certified"] = o.Iso27001Certified
	}
	if !IsNil(o.Iso27001CertificationNum) {
		toSerialize["iso_27001_certification_num"] = o.Iso27001CertificationNum
	}
	if !IsNil(o.IsoExpiryDate) {
		toSerialize["iso_expiry_date"] = o.IsoExpiryDate
	}
	if !IsNil(o.CeCertified) {
		toSerialize["ce_certified"] = o.CeCertified
	}
	if !IsNil(o.CeCertificationNum) {
		toSerialize["ce_certification_num"] = o.CeCertificationNum
	}
	if !IsNil(o.CeExpiryDate) {
		toSerialize["ce_expiry_date"] = o.CeExpiryDate
	}
	if !IsNil(o.CePlusCertified) {
		toSerialize["ce_plus_certified"] = o.CePlusCertified
	}
	if !IsNil(o.CePlusCertificationNum) {
		toSerialize["ce_plus_certification_num"] = o.CePlusCertificationNum
	}
	if !IsNil(o.CePlusExpiryDate) {
		toSerialize["ce_plus_expiry_date"] = o.CePlusExpiryDate
	}
	if !IsNil(o.IdvtResult) {
		toSerialize["idvt_result"] = o.IdvtResult
	}
	if !IsNil(o.IdvtResultPerc) {
		toSerialize["idvt_result_perc"] = o.IdvtResultPerc
	}
	if !IsNil(o.IdvtErrors) {
		toSerialize["idvt_errors"] = o.IdvtErrors
	}
	if !IsNil(o.IdvtCompletedAt) {
		toSerialize["idvt_completed_at"] = o.IdvtCompletedAt
	}
	if !IsNil(o.CompaniesHouseNo) {
		toSerialize["companies_house_no"] = o.CompaniesHouseNo
	}
	if !IsNil(o.SectorId) {
		toSerialize["sector_id"] = o.SectorId
	}
	if !IsNil(o.RorId) {
		toSerialize["ror_id"] = o.RorId
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.SmbStatus) {
		toSerialize["smb_status"] = o.SmbStatus
	}
	if !IsNil(o.OrganisationSize) {
		toSerialize["organisation_size"] = o.OrganisationSize
	}
	if !IsNil(o.Unclaimed) {
		toSerialize["unclaimed"] = o.Unclaimed
	}
	if !IsNil(o.SystemApproved) {
		toSerialize["system_approved"] = o.SystemApproved
	}
	if !IsNil(o.OdsId) {
		toSerialize["ods_id"] = o.OdsId
	}
	if !IsNil(o.DsptkStatus) {
		toSerialize["dsptk_status"] = o.DsptkStatus
	}
	if !IsNil(o.DsptkDateLastPublished) {
		toSerialize["dsptk_date_last_published"] = o.DsptkDateLastPublished
	}
	if !IsNil(o.IcoRegistrationId) {
		toSerialize["ico_registration_id"] = o.IcoRegistrationId
	}
	if !IsNil(o.IcoDateRegistered) {
		toSerialize["ico_date_registered"] = o.IcoDateRegistered
	}
	if !IsNil(o.IcoExpiryDate) {
		toSerialize["ico_expiry_date"] = o.IcoExpiryDate
	}
	return toSerialize, nil
}

type NullableOrganisation struct {
	value *Organisation
	isSet bool
}

func (v NullableOrganisation) Get() *Organisation {
	return v.value
}

func (v *NullableOrganisation) Set(val *Organisation) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganisation) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganisation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganisation(val *Organisation) *NullableOrganisation {
	return &NullableOrganisation{value: val, isSet: true}
}

func (v NullableOrganisation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganisation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


