/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the WebhooksGetAllReceivers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhooksGetAllReceivers200Response{}

// WebhooksGetAllReceivers200Response struct for WebhooksGetAllReceivers200Response
type WebhooksGetAllReceivers200Response struct {
	Message *string `json:"message,omitempty"`
	Data []WebhooksGetAllReceivers200ResponseDataInner `json:"data,omitempty"`
}

// NewWebhooksGetAllReceivers200Response instantiates a new WebhooksGetAllReceivers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksGetAllReceivers200Response() *WebhooksGetAllReceivers200Response {
	this := WebhooksGetAllReceivers200Response{}
	return &this
}

// NewWebhooksGetAllReceivers200ResponseWithDefaults instantiates a new WebhooksGetAllReceivers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksGetAllReceivers200ResponseWithDefaults() *WebhooksGetAllReceivers200Response {
	this := WebhooksGetAllReceivers200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WebhooksGetAllReceivers200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksGetAllReceivers200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WebhooksGetAllReceivers200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WebhooksGetAllReceivers200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WebhooksGetAllReceivers200Response) GetData() []WebhooksGetAllReceivers200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []WebhooksGetAllReceivers200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhooksGetAllReceivers200Response) GetDataOk() ([]WebhooksGetAllReceivers200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WebhooksGetAllReceivers200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []WebhooksGetAllReceivers200ResponseDataInner and assigns it to the Data field.
func (o *WebhooksGetAllReceivers200Response) SetData(v []WebhooksGetAllReceivers200ResponseDataInner) {
	o.Data = v
}

func (o WebhooksGetAllReceivers200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhooksGetAllReceivers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableWebhooksGetAllReceivers200Response struct {
	value *WebhooksGetAllReceivers200Response
	isSet bool
}

func (v NullableWebhooksGetAllReceivers200Response) Get() *WebhooksGetAllReceivers200Response {
	return v.value
}

func (v *NullableWebhooksGetAllReceivers200Response) Set(val *WebhooksGetAllReceivers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksGetAllReceivers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksGetAllReceivers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksGetAllReceivers200Response(val *WebhooksGetAllReceivers200Response) *NullableWebhooksGetAllReceivers200Response {
	return &NullableWebhooksGetAllReceivers200Response{value: val, isSet: true}
}

func (v NullableWebhooksGetAllReceivers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhooksGetAllReceivers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


