/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the OrganisationHasDepartment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganisationHasDepartment{}

// OrganisationHasDepartment Pivot model representing the relationship between organisations and departments
type OrganisationHasDepartment struct {
	// ID of the organisation
	OrganisationId *int32 `json:"organisation_id,omitempty"`
	// ID of the department
	DepartmentId *int32 `json:"department_id,omitempty"`
}

// NewOrganisationHasDepartment instantiates a new OrganisationHasDepartment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganisationHasDepartment() *OrganisationHasDepartment {
	this := OrganisationHasDepartment{}
	return &this
}

// NewOrganisationHasDepartmentWithDefaults instantiates a new OrganisationHasDepartment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganisationHasDepartmentWithDefaults() *OrganisationHasDepartment {
	this := OrganisationHasDepartment{}
	return &this
}

// GetOrganisationId returns the OrganisationId field value if set, zero value otherwise.
func (o *OrganisationHasDepartment) GetOrganisationId() int32 {
	if o == nil || IsNil(o.OrganisationId) {
		var ret int32
		return ret
	}
	return *o.OrganisationId
}

// GetOrganisationIdOk returns a tuple with the OrganisationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationHasDepartment) GetOrganisationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganisationId) {
		return nil, false
	}
	return o.OrganisationId, true
}

// HasOrganisationId returns a boolean if a field has been set.
func (o *OrganisationHasDepartment) HasOrganisationId() bool {
	if o != nil && !IsNil(o.OrganisationId) {
		return true
	}

	return false
}

// SetOrganisationId gets a reference to the given int32 and assigns it to the OrganisationId field.
func (o *OrganisationHasDepartment) SetOrganisationId(v int32) {
	o.OrganisationId = &v
}

// GetDepartmentId returns the DepartmentId field value if set, zero value otherwise.
func (o *OrganisationHasDepartment) GetDepartmentId() int32 {
	if o == nil || IsNil(o.DepartmentId) {
		var ret int32
		return ret
	}
	return *o.DepartmentId
}

// GetDepartmentIdOk returns a tuple with the DepartmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganisationHasDepartment) GetDepartmentIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DepartmentId) {
		return nil, false
	}
	return o.DepartmentId, true
}

// HasDepartmentId returns a boolean if a field has been set.
func (o *OrganisationHasDepartment) HasDepartmentId() bool {
	if o != nil && !IsNil(o.DepartmentId) {
		return true
	}

	return false
}

// SetDepartmentId gets a reference to the given int32 and assigns it to the DepartmentId field.
func (o *OrganisationHasDepartment) SetDepartmentId(v int32) {
	o.DepartmentId = &v
}

func (o OrganisationHasDepartment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganisationHasDepartment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganisationId) {
		toSerialize["organisation_id"] = o.OrganisationId
	}
	if !IsNil(o.DepartmentId) {
		toSerialize["department_id"] = o.DepartmentId
	}
	return toSerialize, nil
}

type NullableOrganisationHasDepartment struct {
	value *OrganisationHasDepartment
	isSet bool
}

func (v NullableOrganisationHasDepartment) Get() *OrganisationHasDepartment {
	return v.value
}

func (v *NullableOrganisationHasDepartment) Set(val *OrganisationHasDepartment) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganisationHasDepartment) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganisationHasDepartment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganisationHasDepartment(val *OrganisationHasDepartment) *NullableOrganisationHasDepartment {
	return &NullableOrganisationHasDepartment{value: val, isSet: true}
}

func (v NullableOrganisationHasDepartment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganisationHasDepartment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


