/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the IdentityIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityIndex200Response{}

// IdentityIndex200Response struct for IdentityIndex200Response
type IdentityIndex200Response struct {
	Message *string `json:"message,omitempty"`
	Data *IdentityIndex200ResponseData `json:"data,omitempty"`
}

// NewIdentityIndex200Response instantiates a new IdentityIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityIndex200Response() *IdentityIndex200Response {
	this := IdentityIndex200Response{}
	return &this
}

// NewIdentityIndex200ResponseWithDefaults instantiates a new IdentityIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityIndex200ResponseWithDefaults() *IdentityIndex200Response {
	this := IdentityIndex200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *IdentityIndex200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityIndex200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *IdentityIndex200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *IdentityIndex200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IdentityIndex200Response) GetData() IdentityIndex200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret IdentityIndex200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityIndex200Response) GetDataOk() (*IdentityIndex200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IdentityIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given IdentityIndex200ResponseData and assigns it to the Data field.
func (o *IdentityIndex200Response) SetData(v IdentityIndex200ResponseData) {
	o.Data = &v
}

func (o IdentityIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableIdentityIndex200Response struct {
	value *IdentityIndex200Response
	isSet bool
}

func (v NullableIdentityIndex200Response) Get() *IdentityIndex200Response {
	return v.value
}

func (v *NullableIdentityIndex200Response) Set(val *IdentityIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityIndex200Response(val *IdentityIndex200Response) *NullableIdentityIndex200Response {
	return &NullableIdentityIndex200Response{value: val, isSet: true}
}

func (v NullableIdentityIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


