/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
)

// checks if the ProjectRoleIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectRoleIndex200Response{}

// ProjectRoleIndex200Response struct for ProjectRoleIndex200Response
type ProjectRoleIndex200Response struct {
	Message *string `json:"message,omitempty"`
	Data *ProjectRole `json:"data,omitempty"`
}

// NewProjectRoleIndex200Response instantiates a new ProjectRoleIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectRoleIndex200Response() *ProjectRoleIndex200Response {
	this := ProjectRoleIndex200Response{}
	return &this
}

// NewProjectRoleIndex200ResponseWithDefaults instantiates a new ProjectRoleIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectRoleIndex200ResponseWithDefaults() *ProjectRoleIndex200Response {
	this := ProjectRoleIndex200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ProjectRoleIndex200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectRoleIndex200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ProjectRoleIndex200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ProjectRoleIndex200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ProjectRoleIndex200Response) GetData() ProjectRole {
	if o == nil || IsNil(o.Data) {
		var ret ProjectRole
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectRoleIndex200Response) GetDataOk() (*ProjectRole, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ProjectRoleIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ProjectRole and assigns it to the Data field.
func (o *ProjectRoleIndex200Response) SetData(v ProjectRole) {
	o.Data = &v
}

func (o ProjectRoleIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectRoleIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableProjectRoleIndex200Response struct {
	value *ProjectRoleIndex200Response
	isSet bool
}

func (v NullableProjectRoleIndex200Response) Get() *ProjectRoleIndex200Response {
	return v.value
}

func (v *NullableProjectRoleIndex200Response) Set(val *ProjectRoleIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectRoleIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectRoleIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectRoleIndex200Response(val *ProjectRoleIndex200Response) *NullableProjectRoleIndex200Response {
	return &NullableProjectRoleIndex200Response{value: val, isSet: true}
}

func (v NullableProjectRoleIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectRoleIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


