/*
Safe People Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package safepeopleregistry-api-sdk

import (
	"encoding/json"
	"time"
)

// checks if the NotificationsGetUserNotifications200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationsGetUserNotifications200ResponseDataInner{}

// NotificationsGetUserNotifications200ResponseDataInner struct for NotificationsGetUserNotifications200ResponseDataInner
type NotificationsGetUserNotifications200ResponseDataInner struct {
	Id *string `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	NotifiableType *string `json:"notifiable_type,omitempty"`
	NotifiableId *int32 `json:"notifiable_id,omitempty"`
	Data *NotificationsGetUserNotifications200ResponseDataInnerData `json:"data,omitempty"`
	ReadAt NullableTime `json:"read_at,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewNotificationsGetUserNotifications200ResponseDataInner instantiates a new NotificationsGetUserNotifications200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationsGetUserNotifications200ResponseDataInner() *NotificationsGetUserNotifications200ResponseDataInner {
	this := NotificationsGetUserNotifications200ResponseDataInner{}
	return &this
}

// NewNotificationsGetUserNotifications200ResponseDataInnerWithDefaults instantiates a new NotificationsGetUserNotifications200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationsGetUserNotifications200ResponseDataInnerWithDefaults() *NotificationsGetUserNotifications200ResponseDataInner {
	this := NotificationsGetUserNotifications200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetNotifiableType returns the NotifiableType field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetNotifiableType() string {
	if o == nil || IsNil(o.NotifiableType) {
		var ret string
		return ret
	}
	return *o.NotifiableType
}

// GetNotifiableTypeOk returns a tuple with the NotifiableType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetNotifiableTypeOk() (*string, bool) {
	if o == nil || IsNil(o.NotifiableType) {
		return nil, false
	}
	return o.NotifiableType, true
}

// HasNotifiableType returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasNotifiableType() bool {
	if o != nil && !IsNil(o.NotifiableType) {
		return true
	}

	return false
}

// SetNotifiableType gets a reference to the given string and assigns it to the NotifiableType field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetNotifiableType(v string) {
	o.NotifiableType = &v
}

// GetNotifiableId returns the NotifiableId field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetNotifiableId() int32 {
	if o == nil || IsNil(o.NotifiableId) {
		var ret int32
		return ret
	}
	return *o.NotifiableId
}

// GetNotifiableIdOk returns a tuple with the NotifiableId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetNotifiableIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NotifiableId) {
		return nil, false
	}
	return o.NotifiableId, true
}

// HasNotifiableId returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasNotifiableId() bool {
	if o != nil && !IsNil(o.NotifiableId) {
		return true
	}

	return false
}

// SetNotifiableId gets a reference to the given int32 and assigns it to the NotifiableId field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetNotifiableId(v int32) {
	o.NotifiableId = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetData() NotificationsGetUserNotifications200ResponseDataInnerData {
	if o == nil || IsNil(o.Data) {
		var ret NotificationsGetUserNotifications200ResponseDataInnerData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetDataOk() (*NotificationsGetUserNotifications200ResponseDataInnerData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NotificationsGetUserNotifications200ResponseDataInnerData and assigns it to the Data field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetData(v NotificationsGetUserNotifications200ResponseDataInnerData) {
	o.Data = &v
}

// GetReadAt returns the ReadAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetReadAt() time.Time {
	if o == nil || IsNil(o.ReadAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ReadAt.Get()
}

// GetReadAtOk returns a tuple with the ReadAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetReadAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadAt.Get(), o.ReadAt.IsSet()
}

// HasReadAt returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasReadAt() bool {
	if o != nil && o.ReadAt.IsSet() {
		return true
	}

	return false
}

// SetReadAt gets a reference to the given NullableTime and assigns it to the ReadAt field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetReadAt(v time.Time) {
	o.ReadAt.Set(&v)
}
// SetReadAtNil sets the value for ReadAt to be an explicit nil
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetReadAtNil() {
	o.ReadAt.Set(nil)
}

// UnsetReadAt ensures that no value is present for ReadAt, not even an explicit nil
func (o *NotificationsGetUserNotifications200ResponseDataInner) UnsetReadAt() {
	o.ReadAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *NotificationsGetUserNotifications200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *NotificationsGetUserNotifications200ResponseDataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o NotificationsGetUserNotifications200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationsGetUserNotifications200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.NotifiableType) {
		toSerialize["notifiable_type"] = o.NotifiableType
	}
	if !IsNil(o.NotifiableId) {
		toSerialize["notifiable_id"] = o.NotifiableId
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.ReadAt.IsSet() {
		toSerialize["read_at"] = o.ReadAt.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableNotificationsGetUserNotifications200ResponseDataInner struct {
	value *NotificationsGetUserNotifications200ResponseDataInner
	isSet bool
}

func (v NullableNotificationsGetUserNotifications200ResponseDataInner) Get() *NotificationsGetUserNotifications200ResponseDataInner {
	return v.value
}

func (v *NullableNotificationsGetUserNotifications200ResponseDataInner) Set(val *NotificationsGetUserNotifications200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationsGetUserNotifications200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationsGetUserNotifications200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationsGetUserNotifications200ResponseDataInner(val *NotificationsGetUserNotifications200ResponseDataInner) *NullableNotificationsGetUserNotifications200ResponseDataInner {
	return &NullableNotificationsGetUserNotifications200ResponseDataInner{value: val, isSet: true}
}

func (v NullableNotificationsGetUserNotifications200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationsGetUserNotifications200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


